import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import type {FeaturePack,FeatureProps} from '../types';
import {boundedNumber,emitFeature,featureError} from '../types';
import {readBounded} from '../fetch';

export function resourceURL(value:string,base:string,allowlist:string[]){const url=new URL(value,base);if(url.protocol==='data:'&&value.length<=16*1024*1024)return value;if(url.protocol==='blob:'&&url.origin===new URL(base).origin)return value;if(url.username||url.password||url.origin!==new URL(base).origin&&(!['https:'].includes(url.protocol)||!allowlist.includes(url.origin)))throw new Error(`3D resource origin denied: ${url.origin}`);if(!['https:','http:'].includes(url.protocol))throw new Error('3D resource protocol denied');return url.href;}
type Controller={camera:(args:any)=>void;select:(name:string)=>void;inspect:()=>any};const controls=new WeakMap<object,Map<string,Controller>>();
function registry(runtime:object){let value=controls.get(runtime);if(!value){value=new Map();controls.set(runtime,value);}return value;}
function tuple(value:any,fallback:number[]){return Array.isArray(value)&&value.length===3&&value.every(Number.isFinite)?value:fallback;}
export function ThreeScene({p,runtime,nodeId}:FeatureProps){
 const host=useRef<HTMLDivElement>(null),props=useRef(p);props.current=p;const [error,setError]=useState('');
 useEffect(()=>{if(!host.current)return;const container=host.current;let renderer:THREE.WebGLRenderer|undefined,frame=0,alive=true;const abort=new AbortController();const disposables:(()=>void)[]=[];
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));container.append(renderer.domElement);renderer.domElement.setAttribute('aria-label',p.ariaLabel??'Interactive 3D view');renderer.domElement.setAttribute('role','img');
   const scene=new THREE.Scene();scene.background=p.background==='transparent'?null:new THREE.Color(p.background??'#eff6ff');const camera=new THREE.PerspectiveCamera(45,1,0.01,10000);camera.position.fromArray(tuple(p.camera?.position,[4,3,6]));camera.lookAt(new THREE.Vector3().fromArray(tuple(p.camera?.target,[0,0,0])));
   const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.enableZoom=p.zoom!==false;orbit.enableRotate=p.orbit!==false;orbit.target.fromArray(tuple(p.camera?.target,[0,0,0]));scene.add(new THREE.HemisphereLight(0xffffff,0x334155,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(4,8,5);scene.add(light);const model=new THREE.Group();scene.add(model);
   const originals=new Map<THREE.Object3D,THREE.Vector3>(),materials=new Map<THREE.Mesh,THREE.Material|THREE.Material[]>();let selected:THREE.Mesh[]=[];const raycast=new THREE.Raycaster();const pointer=new THREE.Vector2();let animation:any=null;
   const remember=(root:THREE.Object3D)=>root.traverse(object=>{originals.set(object,object.position.clone());if(object instanceof THREE.Mesh){materials.set(object,object.material);}});
   const select=(name:string)=>{for(const mesh of selected){if(mesh.material!==materials.get(mesh)){const values=Array.isArray(mesh.material)?mesh.material:[mesh.material];values.forEach(material=>material.dispose());}mesh.material=materials.get(mesh)!;}selected=[];model.traverse(object=>{if(object instanceof THREE.Mesh&&(object.name===name||object.parent?.name===name)){const source=materials.get(object)??object.material;const clones=(Array.isArray(source)?source:[source]).map(material=>{const clone=material.clone();if('emissive' in clone)(clone as THREE.MeshStandardMaterial).emissive.set(props.current.highlightColor??'#0284c7');return clone;});object.material=Array.isArray(source)?clones:clones[0];selected.push(object);}});};
   registry(runtime).set(nodeId,{select,inspect:()=>({camera:{position:camera.position.toArray(),target:orbit.target.toArray()},objects:[...originals.keys()].filter(object=>object.name).map(object=>({name:object.name,visible:object.visible,position:object.position.toArray()}))}),camera:args=>{animation={from:camera.position.clone(),to:new THREE.Vector3().fromArray(tuple(args.position,[4,3,6])),target:new THREE.Vector3().fromArray(tuple(args.target,[0,0,0])),start:performance.now(),duration:boundedNumber(args.duration,700,0,30000)};}});
   const click=(event:MouseEvent)=>{const rect=renderer!.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycast.setFromCamera(pointer,camera);const object=raycast.intersectObject(model,true).find(hit=>{for(let object:THREE.Object3D|null=hit.object;object;object=object.parent)if(!object.visible)return false;return true;})?.object;if(object){const name=object.name||object.parent?.name||object.uuid;select(name);if(props.current.selectionPath)runtime.store.set(props.current.selectionPath,name);emitFeature(runtime,nodeId,'threeSelect',{name,point:object.position.toArray()});}};renderer.domElement.addEventListener('click',click);
   const resize=new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;if(w&&h){renderer!.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}});resize.observe(container);
   const load=async()=>{if(p.src){const url=runtime.assets.resolve(p.src);const manager=new THREE.LoadingManager();manager.setURLModifier(value=>resourceURL(value,new URL('./',url).href,runtime.scene.runtimeOptions?.networkAllowlist??[]));const response=await fetch(url,{signal:abort.signal,credentials:'omit',redirect:'error'});const bytes=await readBounded(response,100*1024*1024);const gltf=await new GLTFLoader(manager).parseAsync(bytes,new URL('./',url).href);if(!alive)return;model.add(gltf.scene);remember(gltf.scene);}else{for(const [index,object]of (p.objects??[{name:'cube',shape:'box'}]).entries()){const geometry=object.shape==='sphere'?new THREE.SphereGeometry(object.radius??0.8,24,16):object.shape==='cylinder'?new THREE.CylinderGeometry(0.5,0.5,1,24):new THREE.BoxGeometry(...tuple(object.size,[1,1,1]) as [number,number,number]);const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:object.color??'#38bdf8',roughness:0.45,metalness:0.05}));mesh.name=object.name??`object-${index}`;mesh.position.fromArray(tuple(object.position,[index*1.5,0,0]));model.add(mesh);}remember(model);}emitFeature(runtime,nodeId,'threeReady',{objects:[...originals.keys()].filter(v=>v.name).map(v=>v.name)});};void load().catch(error=>{if(alive&&!abort.signal.aborted)setError(featureError(error));});
   let lastSelected='',lastCamera=JSON.stringify(p.camera);const render=(now:number)=>{if(!alive)return;const current=props.current;model.rotation.fromArray([...tuple(current.rotation,[0,0,0]),'XYZ'] as any);const explode=boundedNumber(current.explode,0,-1,20);model.traverse(object=>{const original=originals.get(object);if(original){object.position.copy(original).multiplyScalar(1+explode);if(current.visibility&&Object.hasOwn(current.visibility,object.name))object.visible=!!current.visibility[object.name];}});if(current.selected!==undefined&&current.selected!==lastSelected){lastSelected=current.selected;select(lastSelected);}const nextCamera=JSON.stringify(current.camera);if(nextCamera!==lastCamera){lastCamera=nextCamera;animation=null;if(current.camera?.position)camera.position.fromArray(tuple(current.camera.position,[4,3,6]));if(current.camera?.target)orbit.target.fromArray(tuple(current.camera.target,[0,0,0]));}if(animation){const t=animation.duration===0?1:Math.min(1,(now-animation.start)/animation.duration);camera.position.lerpVectors(animation.from,animation.to,t*t*(3-2*t));orbit.target.copy(animation.target);if(t===1)animation=null;}orbit.update();if(!document.hidden)renderer!.render(scene,camera);frame=requestAnimationFrame(render);};frame=requestAnimationFrame(render);
   disposables.push(()=>{orbit.dispose();resize.disconnect();renderer!.domElement.removeEventListener('click',click);model.traverse(object=>{if(object instanceof THREE.Mesh){object.geometry.dispose();const list=new Set([...(Array.isArray(object.material)?object.material:[object.material]),...(Array.isArray(materials.get(object))?materials.get(object) as THREE.Material[]:[materials.get(object)!])]);list.forEach(material=>{if(material){Object.values(material).forEach(value=>{if(value instanceof THREE.Texture)value.dispose();});material.dispose();}});}});});
  }catch(error){setError(featureError(error));}
  return()=>{alive=false;abort.abort();cancelAnimationFrame(frame);registry(runtime).delete(nodeId);disposables.forEach(dispose=>dispose());renderer?.dispose();renderer?.domElement.remove();};
 },[runtime,nodeId,p.src]);
 return <div style={{position:'relative',height:'100%',width:'100%'}}><div ref={host} style={{width:'100%',height:'100%'}}/>{error&&<div role="alert" style={{position:'absolute',inset:0,padding:12,background:'#fff8',color:'#b91c1c'}}>3D unavailable: {error}</div>}</div>;
}
const pack:FeaturePack={id:'three',install(context){context.component('ThreeScene',ThreeScene);for(const method of ['camera','select','inspect'] as const)context.action(`three.${method}`,args=>{const controller=registry(context.runtime).get(args.target);if(!controller)throw new Error('3D component not mounted');if(method==='select')return controller.select(args.name);if(method==='inspect')return controller.inspect();return controller.camera(args);});}};export default pack;
