import {test,expect,type Page} from '@playwright/test';
import {readFileSync,writeFileSync} from 'node:fs';
const expr=(expr:string)=>({expr});
const base=(extra:any={})=>({schemaVersion:1,id:'diagnostic-proof',viewport:{width:1000,height:700},nodes:[],...extra});
async function load(page:Page,scene:any){await page.route('**/diagnostic-proof.json',route=>route.fulfill({json:scene}));await page.goto('/preview.html?spec=diagnostic-proof.json&debug=1');}

test('debug metrics count expanded component/repeat bindings and give a non-mutating density advisory',async({page})=>{
 await page.route('**/bundle-sizes.json',route=>route.fulfill({body:readFileSync('dist/bundle-sizes.json'),contentType:'application/json'}));
 const scene=base({runtimeOptions:{debug:true,canvasThreshold:100},initialState:{count:2},dataSources:{rows:{type:'inline',value:[{id:'a'},{id:'b'}]}},components:{card:{nodes:[{id:'background',type:'Rect',props:{width:50,height:40,fill:'#2563eb'}},{id:'label',type:'Text',props:{width:50,height:40},bind:{text:expr('props.label')}}]}},nodes:[{id:'row',type:'Group',props:{layout:'row',gap:8},repeat:{source:expr('slice(data.rows,0,state.count)'),item:'row',key:expr('row.id')},children:[{id:'card',type:'component',component:'card',repeat:{source:expr('range(20)'),item:'column',key:expr('column')},props:{label:expr('row.id+column')}}]}]});
 await load(page,scene);const output=page.locator('.diagnostics');await expect(output).toHaveAttribute('data-rendered-nodes','122');await expect(output).toHaveAttribute('data-bindings','80');await expect(output).toContainText('consider explicit Canvas');await expect(output).toContainText('code: JS');expect(await page.locator('canvas').count()).toBe(0);
 await page.evaluate(()=>window.__interactive.runtime.store.set('count',1));await expect(output).toHaveAttribute('data-rendered-nodes','61');await expect(output).toHaveAttribute('data-bindings','40');await expect(output).not.toContainText('consider explicit Canvas');
});

test('debug error context identifies scene, node, expression and asset without replacing production fallback',async({page})=>{
 await load(page,base({runtimeOptions:{debug:true},nodes:[{id:'faulty',type:'Rect',bind:{width:expr('missing_function(state.value)')}}]}));await expect(page.getByRole('alert')).toContainText('Static slide content remains available.');const details=JSON.parse(await page.locator('[data-diagnostic]').innerText());expect(details).toMatchObject({sceneId:'diagnostic-proof',nodeId:'faulty',expression:'missing_function(state.value)'});expect(details.stack).toContain('Error');
 await page.unroute('**/diagnostic-proof.json');await page.route('**/missing.png',route=>route.fulfill({status:404,body:'missing'}));await load(page,base({assets:{portrait:{path:'missing.png'}}}));await expect(page.getByRole('alert')).toContainText('Interactive content unavailable.');expect(await page.evaluate(()=>window.__interactive.diagnostic)).toMatchObject({sceneId:'diagnostic-proof',asset:'portrait',phase:'asset'});
});

test('500 repeated marks record frame and real-input DOM latency while drag, slider and timeline finish correctly',async({page},info)=>{
 test.setTimeout(45000);
 const scene=base({runtimeOptions:{debug:true,canvasThreshold:500},initialState:{dragX:0,gain:50,t:0},nodes:[
  {id:'marks',type:'Group',props:{x:20,y:90,width:620,height:470},bind:{x:expr('20+state.dragX+state.t')},children:[{id:'surface',type:'Rect',props:{width:620,height:470,fill:'#e2e8f0'}},{id:'mark',type:'Rect',props:{width:18,height:16,fill:'#2563eb'},repeat:{source:expr('range(500)'),item:'item',key:expr('item')},bind:{x:expr('(index%25)*24+10'),y:expr('floor(index/25)*23+8'),opacity:expr('.3+state.gain/100*.7')}}]},
  {id:'gain',type:'Slider',props:{x:30,y:600,width:450,height:45,min:0,max:100,step:1,ariaLabel:'Performance gain'},bind:{value:expr('state.gain')}},
  {id:'label',type:'Text',props:{x:30,y:20,width:800,height:45,text:'500 marks · parent drag/timeline · per-mark slider opacity',fontSize:24}}
 ],behaviors:[{type:'drag',target:'marks',axis:'x',xPath:'dragX',bounds:{xMin:0,xMax:180}}],interactions:[{target:'gain',event:'input',actions:[{type:'set',path:'gain',value:expr('event.value')}]}],timelines:[{id:'move',duration:1000,tracks:[{path:'t',keyframes:[{time:0,value:0},{time:1000,value:100}]}]}]});
 await load(page,scene);await expect(page.locator('[data-node-id]')).toHaveCount(504);await expect(page.locator('.diagnostics')).toHaveAttribute('data-rendered-nodes','504');
 await page.evaluate(()=>{const measurements=(window as any).__measurements={phase:'warmup',frames:{drag:[],slider:[],timeline:[]},latencies:{drag:[],slider:[]},lastInput:0,raf:0};const marks=document.querySelector('[data-node-id="marks"]')!,mark=document.querySelector('[data-node-id="0-mark"]')!;
  const record=()=>{if(measurements.lastInput&&measurements.latencies[measurements.phase]){measurements.latencies[measurements.phase].push(performance.now()-measurements.lastInput);measurements.lastInput=0;}};new MutationObserver(record).observe(marks,{attributes:true,attributeFilter:['transform']});new MutationObserver(record).observe(mark,{attributes:true,attributeFilter:['opacity']});document.addEventListener('pointermove',()=>{if(measurements.phase==='drag')measurements.lastInput=performance.now();},true);document.addEventListener('input',()=>{if(measurements.phase==='slider')measurements.lastInput=performance.now();},true);
  let last=performance.now();const tick=(time:number)=>{const active=measurements.phase!=='timeline'||window.__interactive.runtime.timeline.states.move?.playing;if(active&&measurements.frames[measurements.phase]&&time>=last)measurements.frames[measurements.phase].push(time-last);last=Math.max(last,time);measurements.raf=requestAnimationFrame(tick);};measurements.raf=requestAnimationFrame(tick);
 });
 await page.waitForTimeout(200);await page.evaluate(()=>(window as any).__measurements.phase='drag');const box=await page.locator('[data-node-id="surface"]').boundingBox();if(!box)throw new Error('Missing drag surface');const scale=box.width/620;await page.mouse.move(box.x+15*scale,box.y+15*scale);await page.mouse.down();for(let i=1;i<=30;i++){await page.mouse.move(box.x+(15+i*3)*scale,box.y+15*scale);await page.waitForTimeout(16);}await page.mouse.up();expect(await page.evaluate(()=>window.__interactive.runtime.store.get('dragX'))).toBeCloseTo(90);
 await page.evaluate(()=>(window as any).__measurements.phase='slider');await page.getByRole('slider',{name:'Performance gain'}).focus();for(let i=0;i<20;i++){await page.keyboard.press('ArrowRight');await page.waitForTimeout(16);}expect(await page.evaluate(()=>window.__interactive.runtime.store.get('gain'))).toBe(70);expect(Number(await page.locator('[data-node-id="0-mark"]').getAttribute('opacity'))).toBeCloseTo(.79);
 await page.evaluate(()=>{(window as any).__measurements.phase='timeline';return window.__interactive.dispatch([{type:'playTimeline',timeline:'move'}]);});await expect.poll(()=>page.evaluate(()=>window.__interactive.runtime.store.get('t'))).toBe(100);
 const raw=await page.evaluate(()=>{const m=(window as any).__measurements;cancelAnimationFrame(m.raf);return{frames:m.frames,latencies:m.latencies,visibility:document.visibilityState,userAgent:navigator.userAgent,hardwareConcurrency:navigator.hardwareConcurrency,metrics:window.__interactive.runtime.metrics};});
 const stats=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return{samples:values.length,medianMs:sorted[Math.floor((sorted.length-1)*.5)]??0,p95Ms:sorted[Math.floor((sorted.length-1)*.95)]??0,maxMs:sorted.at(-1)??0,over33ms:values.filter(v=>v>33.34).length};};
 const report={measuredAt:new Date().toISOString(),baseURL:page.url(),hostPlatform:process.platform,hostArchitecture:process.arch,...raw,frameIntervals:Object.fromEntries(Object.entries(raw.frames).map(([key,values])=>[key,stats(values as number[])])),inputToDOM:Object.fromEntries(Object.entries(raw.latencies).map(([key,values])=>[key,stats(values as number[])])),meaning:'rAF intervals during interaction (timeline samples only while playing) and real pointer/keyboard input-to-observed SVG attribute mutation; a bounded hardware-specific sample, not a universal 60fps guarantee'};
 writeFileSync(info.outputPath('performance.json'),JSON.stringify(report,null,2));await page.screenshot({path:info.outputPath('performance-final.png')});expect(raw.visibility).toBe('visible');expect(raw.latencies.drag.length).toBeGreaterThan(10);expect(raw.latencies.slider.length).toBeGreaterThan(10);expect(raw.frames.timeline.length).toBeGreaterThan(10);expect(await page.evaluate(()=>window.__interactive.runtime.error)).toBeNull();
});
