import {describe,it,expect,vi} from 'vitest';
import {SceneStore} from '../../src/core/store';
import {TimelineEngine} from '../../src/core/timeline';
import {ComputeLoop} from '../../src/core/compute';
import {Runtime} from '../../src/core/runtime';
import {ActionDispatcher} from '../../src/core/actions';
import {EventBus} from '../../src/core/events';
import {DataLayer} from '../../src/core/data';
import {ComponentRegistry,registerComponents,geo} from '../../src/components/registry';
import {validateScene} from '../../src/core/schema';
const fixture=(rest:any={})=>({schemaVersion:1 as const,id:'test',viewport:{width:1000,height:700},nodes:[],...rest});

describe('runtime semantic regressions',()=>{
 it('accepts an animation-frame timestamp just before the request clock on start and resume',()=>{const callbacks:FrameRequestCallback[]=[];let serial=0;vi.stubGlobal('requestAnimationFrame',(fn:FrameRequestCallback)=>{callbacks.push(fn);return ++serial;});vi.stubGlobal('cancelAnimationFrame',vi.fn());const clock=vi.spyOn(performance,'now').mockReturnValue(1000),errors=vi.fn(),store=new SceneStore({x:0}),timeline=new TimelineEngine([{id:'move',duration:1000,tracks:[{path:'x',keyframes:[{time:0,value:0},{time:1000,value:100}]}]}],store,()=>{},false,errors);timeline.play('move');callbacks.shift()!(999.5);expect(store.get('x')).toBe(0);expect(timeline.states.move.playing).toBe(true);callbacks.shift()!(1016.6);expect(store.get('x')).toBeCloseTo(1.66);timeline.pause('move');callbacks.shift()!(1033);clock.mockReturnValue(2000);timeline.play('move');callbacks.shift()!(1999.5);callbacks.shift()!(2016.6);expect(store.get('x')).toBeCloseTo(3.32);expect(errors).not.toHaveBeenCalled();timeline.dispose();callbacks.length=0;const events:any[]=[],compute=new ComputeLoop({move:[]},(_,event)=>events.push(event));compute.start('move');callbacks.shift()!(1999.5);callbacks.shift()!(2016.6);expect(events[0]).toMatchObject({deltaTime:0,elapsedTime:0});expect(events[1].deltaTime).toBeCloseTo(.0166);compute.dispose();clock.mockRestore();vi.unstubAllGlobals();});
 it('rolls back failed nested writes and derived recomputation atomically',()=>{const store=new SceneStore({x:1},{safe:{expr:'state.x > 2 ? missing() : state.x*2'}});const listener=vi.fn();store.subscribe(env=>env.state,listener);expect(()=>store.batch(()=>{store.set('x',3);store.set('extra',true);})).toThrow();expect(store.get()).toEqual({x:1,safe:2});expect(listener).not.toHaveBeenCalled();store.set('x',2);expect(store.get('safe')).toBe(4);expect(listener).toHaveBeenCalledTimes(1);});
 it('activates derived state only after plugin functions register; custom functions use current expression context',async()=>{const runtime=new Runtime(fixture({initialState:{x:4},functions:{times:{params:['value'],expr:'value*state.x'}},derivedState:{computed:{expr:'customValue(times(3))'}}}));runtime.expressions.functions.register('customValue',(v:number)=>v+1);await runtime.initialize();expect(runtime.store.get('computed')).toBe(13);runtime.store.set('x',5);expect(runtime.store.get('computed')).toBe(16);runtime.dispose();});
 it('awaits custom action completion before following actions',async()=>{const store=new SceneStore(),actions=new ActionDispatcher(store,new EventBus());actions.register('plugin',async()=>{await new Promise(resolve=>setTimeout(resolve,5));store.set('received',4);});await actions.run([{type:'plugin',name:'extension.run'},{type:'set',path:'after',value:{expr:'state.received+1'}}]);expect(store.get('after')).toBe(5);});
 it('call actions preserve current state, data, event and repeat locals through nested registered functions',async()=>{const runtime=new Runtime(fixture({initialState:{n:7},dataSources:{rows:{type:'inline',value:[3]}},functions:{inner:{params:['x'],expr:'state.n+x+data.rows[0]+event.value+item.offset'},outer:{params:['x'],expr:'inner(x)*2'},broken:{params:[],expr:'missing()'}}}));await runtime.initialize();await runtime.dispatch([{type:'call',name:'outer',args:[2],result:'answer'}],{value:5},{item:{offset:11}});expect(runtime.store.get('answer')).toBe(56);expect(runtime.expressions.context()).toEqual({state:{},data:{}});await expect(runtime.dispatch([{type:'call',name:'broken'}],{value:99},{item:{offset:99}})).rejects.toThrow('missing');expect(runtime.expressions.context()).toEqual({state:{},data:{}});runtime.dispose();});
 it('retains external data on state reset and invalidates atomic failed snapshots',()=>{const store=new SceneStore({x:1});store.setData('rows',[{x:2}]);store.set('x',3);store.reset();expect(store.getData().rows).toEqual([{x:2}]);expect(store.get('x')).toBe(1);expect(()=>store.restore({state:JSON.parse('{"constructor":1}'),data:{}})).toThrow();expect(store.get('x')).toBe(1);});
 it('consumes partial delays, loops without losing remaining time and supports reverse/seek/replay',()=>{vi.stubGlobal('requestAnimationFrame',vi.fn(()=>1));vi.stubGlobal('cancelAnimationFrame',vi.fn());const store=new SceneStore({x:0,speed:2}),marks=vi.fn(),timeline=new TimelineEngine([{id:'move',duration:1000,delay:100,loop:true,bind:{playbackRate:{expr:'state.speed'}},tracks:[{path:'x',keyframes:[{time:0,value:0},{time:1000,value:100}]}],markers:[{time:500,actions:[{type:'increment',path:'m'}]}]}],store,marks);timeline.play('move');timeline.advance(150);expect(store.get('x')).toBe(10);timeline.advance(500);expect(store.get('x')).toBe(10);expect(marks).toHaveBeenCalledTimes(1);timeline.stop('move');expect(store.get('x')).toBe(0);timeline.play('move');timeline.advance(100);expect(store.get('x')).toBe(0);timeline.dispose();vi.unstubAllGlobals();});
 it('rejects empty timeline tracks and permits bounded plugin action/source configuration',()=>{expect(()=>validateScene(fixture({timelines:[{id:'empty',duration:100,tracks:[{path:'x',keyframes:[]}]}]}))).toThrow();expect(validateScene(fixture({dataSources:{pluginData:{type:'plugin',adapter:'custom.rows',options:{n:2}}},interactions:[{target:'scene',event:'click',actions:[{type:'plugin',name:'custom.run',value:2}]}]}))).toBeTruthy();});
 it('accepts named plugin arguments while retaining positional-only function calls',()=>{const scene=(type:string,args:any)=>fixture({interactions:[{target:'scene',event:'click',actions:[{type,name:type==='plugin'?'code.setCode':'sum',args}]}]});expect(validateScene(scene('plugin',{code:{expr:'state.code'},target:'editor'}))).toBeTruthy();expect(validateScene(scene('call',[[2,3]]))).toBeTruthy();expect(()=>validateScene(scene('call',{values:[2,3]}))).toThrow('Invalid scene');});
 it('bounds recursive event actions without unhandled promise rejection',async()=>{const runtime=new Runtime(fixture({runtimeOptions:{maxActions:8},interactions:[{target:'scene',event:'loop',actions:[{type:'emit',event:'loop'}]}]}));await runtime.initialize();runtime.emit({type:'loop',target:'scene',timestamp:0});await new Promise(resolve=>setTimeout(resolve,0));expect(runtime.error).toContain('Action transaction limit');runtime.dispose();});
});

describe('data and first-party components',()=>{
 it('loads joined data in dependency order and retains last-known rows after a failed refresh',async()=>{let fail=false;vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(fail)throw new Error('offline');await new Promise(resolve=>setTimeout(resolve,url.includes('b.json')?10:0));return new Response(JSON.stringify(url.includes('b.json')?[{id:1,name:'one'}]:[{id:1,value:3}]),{headers:{'content-type':'application/json'}});}));const store=new SceneStore();const data=new DataLayer({a:{type:'json',path:'a.json',transforms:[{type:'join',source:'b',key:'id'}]},b:{type:'json',path:'b.json'}},store,'https://localhost/');await data.initialize();expect(store.getData().a[0].joined.name).toBe('one');fail=true;await data.load('a');expect(store.getData().a[0].value).toBe(3);expect(store.get('_dataStatus.a.error')).toContain('offline');data.dispose();vi.unstubAllGlobals();});
 it('ignores a stale fetch resolving after a newer refresh',async()=>{const resolvers:((value:Response)=>void)[]=[];vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(resolve=>resolvers.push(resolve))));const store=new SceneStore(),data=new DataLayer({a:{type:'json',path:'a.json'}},store,'https://localhost/');const old=data.load('a'),current=data.load('a');resolvers[1](new Response('[2]'));await current;resolvers[0](new Response('[1]'));await old;expect(store.getData().a).toEqual([2]);data.dispose();vi.unstubAllGlobals();});
 it('generates finite signed bars, object tables, theme color and selection metadata',()=>{const registry=new ComponentRegistry();registerComponents(registry);const bars=registry.render('stackedBarChart',{data:[{label:'A',values:[3,-2]}],width:300,height:200,selected:0},{accent:'#004455'});expect(bars[0].props!.fill).toBe('#004455');expect(bars.slice(0,2).every(node=>node.props!.height>0)).toBe(true);expect(bars[1].props!.eventValue).toMatchObject({index:0,series:1,value:-2});expect(bars[0].props!.strokeWidth).toBe(3);const table=registry.render('table',{columns:[{key:'id',label:'ID'}],data:[{id:7}]},{});expect(table.at(-1)!.props!.text).toBe('7');});
 it('supports map layers, holes, all core geometry types and meaningful feature IDs',()=>{const nodes=geo({layers:[{id:'hidden',visible:false,data:{features:[{geometry:{type:'Unknown'}}]}},{id:'main',data:{features:[{id:'island',properties:{name:'An island'},geometry:{type:'Polygon',coordinates:[[[0,0],[10,0],[10,10],[0,0]],[[2,2],[3,2],[2,3],[2,2]]]}}]}}],selected:'island'});expect(nodes).toHaveLength(1);expect(nodes[0].props).toMatchObject({fillRule:'evenodd',strokeWidth:3,eventValue:{id:'island',layer:'main'}});expect(nodes[0].props!.d.split('M')).toHaveLength(3);expect(()=>geo({data:{features:[{geometry:{type:'Point',coordinates:['bad',2]}}]}})).toThrow('finite');});
});
