import type {Dict} from './types';
import {safeKey} from './state';
import {Expressions} from './expressions';
import {SceneStore} from './store';
import {allowedUrl} from './assets';
export function parseCSV(input:string){const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<input.length;i++){const c=input[i];if(c==='"'){if(quoted&&input[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c===','||c==='\n')){row.push(field.replace(/\r$/,''));field='';if(c==='\n'){rows.push(row);row=[];}}else field+=c;}if(quoted)throw new Error('Unclosed CSV quote');if(field||row.length){row.push(field);rows.push(row);}const headers=rows.shift()??[];headers.forEach(safeKey);if(new Set(headers).size!==headers.length)throw new Error('Duplicate CSV header');return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}
export function transformData(input:any,steps:Dict[],ex:Expressions,env:Dict){let value=input;for(const step of steps){const expression=(item:any,index:number,e=step.expr)=>ex.evaluate(e,{...env,locals:{item,index}} as any);switch(step.type){case 'filter':value=value.filter((v:any,i:number)=>expression(v,i));break;case 'map':case 'select':value=value.map((v:any,i:number)=>expression(v,i));break;case 'sort':value=[...value].sort((a,b)=>{const x=a[step.key],y=b[step.key];return (x<y?-1:x>y?1:0)*(step.descending?-1:1);});break;case 'slice':value=value.slice(step.start,step.end);break;case 'groupBy':{const g:Dict=Object.create(null);for(const row of value){const k=safeKey(String(row[step.key]));(g[k]??=[]).push(row);}value=g;break;}case 'aggregate':{const a=step.key?value.map((v:any)=>Number(v[step.key])):value;value=step.operation==='count'?value.length:ex.functions.call(step.operation??'sum',[a]);break;}case 'lookup':value=value.find((v:any)=>v[step.key]===step.value)??null;break;case 'join':{const rows=env.data[step.source]??[];value=value.flatMap((a:any)=>rows.filter((b:any)=>a[step.key]===b[step.foreignKey??step.key]).map((b:any)=>({...a,[step.as??'joined']:b})));break;}default:throw new Error(`Unknown transform ${step.type}`);}}return value;}
export class DataLayer {
 status:Dict={};private connections:(EventSource|WebSocket)[]=[];private timers:any[]=[];private abort=new AbortController();private custom=new Map<string,(s:Dict)=>Promise<any>>();
 constructor(private sources:Dict,private store:SceneStore,private base:string,private allowlist:string[]=[]){ }
 register(name:string,fn:(s:Dict)=>Promise<any>){if(this.custom.has(name))throw new Error('Duplicate data adapter');this.custom.set(name,fn);}
 async initialize(){await Promise.all(Object.keys(this.sources).map(k=>this.load(k)));for(const [name,s]of Object.entries(this.sources))if(s.refreshMs)this.timers.push(setInterval(()=>void this.load(name),s.refreshMs));}
 async load(name:string){const s=this.sources[name];if(!s)throw new Error(`Unknown data source: ${name}`);this.status[name]={loading:true,error:null};try{let value=s.value;if(this.custom.has(s.type))value=await this.custom.get(s.type)!(s);else if(s.type!=='inline'){const url=allowedUrl(s.path??s.url,this.base,this.allowlist);if(['sse','websocket'].includes(s.type)){const connection=s.type==='sse'?new EventSource(url):new WebSocket(url);connection.onmessage=(event)=>{try{this.publish(name,JSON.parse(event.data),s);}catch(error){this.status[name]={loading:false,error:String(error)};}};connection.onerror=()=>{this.status[name]={loading:false,error:'Connection unavailable; retaining last data'};};this.connections.push(connection);value=s.fallback??[];}else{const response=await fetch(url,{redirect:'error',credentials:'omit',signal:this.abort.signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);const body=await response.text();if(body.length>8*1024*1024)throw new Error('Data too large');value=s.type==='csv'?parseCSV(body):JSON.parse(body);}}this.publish(name,value,s);}catch(error){this.status[name]={loading:false,error:String(error)};if(this.store.getData()[name]===undefined)this.store.setData(name,s.fallback??[]);}}
 private publish(name:string,value:any,source:Dict){this.store.setData(name,transformData(value,source.transforms??[],this.store.expressions,this.store.environment()));this.status[name]={loading:false,error:null,updatedAt:Date.now()};}
 dispose(){this.abort.abort();this.connections.forEach(c=>c.close());this.timers.forEach(clearInterval);}
}
