import type {Scene,Dict,Action,EventContext} from './types';
import {validateScene} from './schema';
import {SceneStore} from './store';
import {Expressions} from './expressions';
import {EventBus} from './events';
import {ActionDispatcher} from './actions';
import {TimelineEngine} from './timeline';
import {Behaviors} from './behaviors';
import {ComputeLoop,seededRNG} from './compute';
import {DataLayer} from './data';
import {Assets} from './assets';
import {ComponentRegistry,registerComponents} from '../components/registry';
export class Runtime {
 scene:Scene;store:SceneStore;expressions=new Expressions();events=new EventBus();actions:ActionDispatcher;timeline:TimelineEngine;behaviors:Behaviors;compute:ComputeLoop;data:DataLayer;assets:Assets;components=new ComponentRegistry();mediaElements=new Map<string,HTMLMediaElement>();timers:any[]=[];error:string|null=null;onError:((e:Error)=>void)|null=null;ready=false;plugins:(()=>void)[]=[];
 constructor(input:Scene,public base=typeof location==='undefined'?'https://localhost:41973/deck/':new URL('./',location.href).href){this.scene=validateScene(input);const rng=seededRNG(this.scene.runtimeOptions?.seed??1);this.expressions.functions.register('random',rng);for(const [name,f]of Object.entries(this.scene.functions??{}))this.expressions.functions.register(name,(...args)=>this.expressions.evaluate(f.expr,this.store.environment(Object.fromEntries(f.params.map((p,i)=>[p,args[i]])))));this.store=new SceneStore(this.scene.initialState,this.scene.derivedState,this.expressions,Object.fromEntries(Object.entries(this.scene.dataSources??{}).map(([k,v])=>[k,v.value??v.fallback??[]])));this.actions=new ActionDispatcher(this.store,this.events,this.scene.runtimeOptions?.maxActions);this.timeline=new TimelineEngine(this.scene.timelines??[],this.store,a=>void this.dispatch(a),this.scene.runtimeOptions?.reducedMotion??(typeof matchMedia!=='undefined'&&matchMedia('(prefers-reduced-motion: reduce)').matches));this.compute=new ComputeLoop(this.scene.runtimeOptions?.loops??{},(a,e)=>void this.dispatch(a,e));this.assets=new Assets(this.scene,base);this.data=new DataLayer(this.scene.dataSources??{},this.store,base,this.scene.runtimeOptions?.networkAllowlist??[]);this.behaviors=new Behaviors(this.scene.behaviors??[],this.store,(a,e)=>void this.dispatch(a,e));this.actions.services={timeline:this.timeline,compute:this.compute,data:this.data,base,allowlist:this.scene.runtimeOptions?.networkAllowlist??[],reset:()=>{for(const id of Object.keys(this.timeline.states))this.timeline.stop(id);this.compute.dispose();},media:(id:string,method:string,value:any)=>{const media=this.mediaElements.get(id);if(!media)throw new Error('Media not mounted');if(method==='play')void media.play().catch(e=>this.fail(e));else if(method==='pause')media.pause();else if(['currentTime','playbackRate','volume','muted'].includes(method))(media as any)[method]=value;else throw new Error('Unsupported media action');}};registerComponents(this.components);for(const [name,c]of Object.entries(this.scene.components??{}))this.components.register(name,(props)=>c.nodes.map(n=>({...n,props:this.expressions.value(n.props??{},this.store.environment({props}))})));this.events.on('*',event=>{for(const rule of this.scene.interactions??[])if((rule.target===event.target||rule.target==='*'||rule.target==='scene'&&event.target==='scene')&&rule.event===event.type&&(!rule.when||this.expressions.value(rule.when,this.store.environment(event.locals,event))))void this.dispatch(rule.actions,event,event.locals);});}
 async initialize(){await this.assets.verify();await this.data.initialize();for(const t of this.scene.runtimeOptions?.timers??[])this.timers.push(setInterval(()=>this.emit({type:'timer',name:t.event,target:'scene',timestamp:performance.now()}),t.interval));this.ready=true;}
 async dispatch(actions:Action[],event:Dict={},locals:Dict={}){try{await this.actions.run(actions,event,locals);}catch(error){this.fail(error);throw error;}}
 emit(event:EventContext,node?:Dict){try{if(node)this.behaviors.handle(event,node);this.events.emit(event);}catch(error){this.fail(error);}}
 fail(error:any){this.error=String(error);this.onError?.(error instanceof Error?error:new Error(String(error)));}
 dispose(){this.actions.dispose();this.timeline.dispose();this.compute.dispose();this.data.dispose();this.assets.dispose();this.events.dispose();this.store.dispose();this.timers.forEach(clearInterval);this.plugins.forEach(dispose=>dispose());}
}
