import type {Locale} from './i18n';
import type {phases} from './progress';
type Words={overview:string;design:string;current:string;next:string;pages:string;ready:string;waiting:string;empty:string;history:string;more:string;less:string;hint:string;phase:Record<typeof phases[number],string>};
export const creationWords:Record<Locale,Words>={
 'zh-CN':{overview:'设计与进度',design:'设计方向',current:'正在做什么',next:'接下来',pages:'逐页预览',ready:'已有预览',waiting:'等待制作',empty:'尚未收到设计说明。新的阶段更新会显示在这里。',history:'制作过程',more:'查看更早的说明',less:'收起较早说明',hint:'页面渲染后即可预览，修改后会更新。整份检查通过后提供成品下载。',phase:{research:'资料整理',planning:'内容规划',design:'设计说明',building:'页面制作',rendering:'页面渲染',review:'检查与调整'}},
 en:{overview:'Design & progress',design:'Design direction',current:'Current work',next:'Up next',pages:'Page-by-page previews',ready:'Preview available',waiting:'Not started',empty:'No design notes yet. New stage updates will appear here.',history:'Creation updates',more:'Show earlier updates',less:'Hide earlier updates',hint:'Previews appear after each page is rendered and update after revisions. Download follows the full-deck checks.',phase:{research:'Research',planning:'Content plan',design:'Design decision',building:'Building a page',rendering:'Rendering',review:'Review & refinement'}},
 fr:{overview:'Design et progression',design:'Direction visuelle',current:'Travail en cours',next:'À suivre',pages:'Aperçus par page',ready:'Aperçu disponible',waiting:'À réaliser',empty:'Aucune note de conception pour le moment.',history:'Étapes de création',more:'Voir les notes précédentes',less:'Masquer les anciennes notes',hint:'Chaque page apparaît après son rendu, puis est actualisée après modification. Le téléchargement suit la vérification complète.',phase:{research:'Recherche',planning:'Plan du contenu',design:'Choix visuel',building:'Création de page',rendering:'Rendu',review:'Vérification et ajustement'}},
 es:{overview:'Diseño y progreso',design:'Dirección visual',current:'Trabajo actual',next:'A continuación',pages:'Vistas por página',ready:'Vista disponible',waiting:'Por crear',empty:'Aún no hay notas de diseño. Las actualizaciones aparecerán aquí.',history:'Proceso de creación',more:'Ver notas anteriores',less:'Ocultar notas anteriores',hint:'Cada página aparece al renderizarse y se actualiza tras las revisiones. La descarga sigue a la revisión completa.',phase:{research:'Investigación',planning:'Plan de contenido',design:'Decisión de diseño',building:'Creación de página',rendering:'Renderizado',review:'Revisión y ajustes'}},
 ja:{overview:'デザインと進捗',design:'デザイン方針',current:'現在の作業',next:'次の作業',pages:'ページごとのプレビュー',ready:'プレビューあり',waiting:'作成待ち',empty:'デザイン説明はまだありません。進捗が届くとここに表示されます。',history:'制作の進捗',more:'以前の説明を表示',less:'以前の説明を閉じる',hint:'各ページの描画後にプレビューが表示され、修正後に更新されます。全体の確認後にダウンロードできます。',phase:{research:'資料調査',planning:'内容の計画',design:'デザイン説明',building:'ページ制作',rendering:'レンダリング',review:'確認と調整'}},
};
