import type {Locale} from './i18n';
import {MAX_SLIDES} from './slide-limits.mjs';
type Copy={help:string;fromBrief:(n:number)=>string;fromInput:(n:number)=>string;pagesRange:string;pagesAmbiguous:string};
export const pageCountMessages:Record<Locale,Copy>={
 'zh-CN':{help:`可输入 1–${MAX_SLIDES} 页。需求中明确写了总页数时，以需求为准；未写时使用这里的页数。`,fromBrief:n=>`本次将制作 ${n} 页，采用需求中明确指定的页数。`,fromInput:n=>`本次将制作 ${n} 页。`,pagesRange:`请输入 1–${MAX_SLIDES} 的整数页数；需求中指定的页数也需在此范围内。`,pagesAmbiguous:'需求中的页数存在多个值或范围，请写明一个最终总页数后再提交。'},
 en:{help:`Enter 1–${MAX_SLIDES} slides. An explicit total in your brief takes priority; otherwise this number is used.`,fromBrief:n=>`This presentation will have ${n} slides, as specified in your brief.`,fromInput:n=>`This presentation will have ${n} slides.`,pagesRange:`Enter a whole number from 1 to ${MAX_SLIDES}. Counts in the brief must also be within this range.`,pagesAmbiguous:'Your brief contains multiple totals or a range. Specify one final total before submitting.'},
 fr:{help:`Saisissez 1 à ${MAX_SLIDES} diapositives. Un total explicite dans le brief est prioritaire ; sinon, ce nombre sera utilisé.`,fromBrief:n=>`La présentation comportera ${n} diapositives, selon votre brief.`,fromInput:n=>`La présentation comportera ${n} diapositives.`,pagesRange:`Saisissez un entier entre 1 et ${MAX_SLIDES}, y compris dans le brief.`,pagesAmbiguous:'Le brief contient plusieurs totaux ou un intervalle. Précisez un seul total final.'},
 es:{help:`Introduce entre 1 y ${MAX_SLIDES} diapositivas. El total explícito del encargo tiene prioridad; si no lo hay, se usa este número.`,fromBrief:n=>`La presentación tendrá ${n} diapositivas, según tu encargo.`,fromInput:n=>`La presentación tendrá ${n} diapositivas.`,pagesRange:`Introduce un entero entre 1 y ${MAX_SLIDES}, también si lo indicas en el encargo.`,pagesAmbiguous:'El encargo contiene varios totales o un intervalo. Indica un único total final.'},
 ja:{help:`1〜${MAX_SLIDES}枚を入力してください。依頼文に総枚数が明記されている場合はそちらを優先し、それ以外はこの枚数を使います。`,fromBrief:n=>`依頼文の指定に従い、${n}枚で作成します。`,fromInput:n=>`${n}枚で作成します。`,pagesRange:`依頼文の指定も含め、1〜${MAX_SLIDES}の整数を入力してください。`,pagesAmbiguous:'依頼文に複数の総枚数または範囲があります。最終的な総枚数を1つ指定してください。'}
};
