import type {Locale} from './i18n';
export const sourceFileLabels:Record<Locale,string>={en:'Original PPTX (required) and references',fr:'PPTX original (obligatoire) et références',es:'PPTX original (obligatorio) y referencias','zh-CN':'原始 PPTX（必需）与参考资料',ja:'元のPPTX（必須）と参考資料'};
type Copy={label:string;create:string;edit:string;createHelp:string;editHelp:string;pages:string;automatic:string;missing:string;placeholder:string};
export const taskModeMessages:Record<Locale,Copy>={
 en:{label:'What would you like to do?',create:'Create a new presentation',edit:'Edit or extend an existing PPT',createHelp:'Start from your brief, uploaded references, or web research. Uploads are optional.',editHelp:'Upload one original PPTX plus optional references. Describe what to change or add; unrelated slides will be preserved.',pages:'Target slides for the new presentation',automatic:'No slide count needed. The brief determines which slides to modify and how many to add.',missing:'Please upload exactly one original .pptx to edit. Other reference formats are welcome.',placeholder:'What should change? Name slides or sections, explain what to add, and what should stay unchanged.'},
 'zh-CN':{label:'你想如何制作？',create:'从零新建 PPT',edit:'修改或扩充已有 PPT',createHelp:'根据需求、上传资料或网上搜索制作新 PPT；资料可选上传。',editHelp:'上传一份原始 PPTX，可附其他参考资料。说明需要修改或添加的内容，保留与任务无关的页面。',pages:'新 PPT 的期望总页数',automatic:'无需选择页数。根据具体需求决定修改哪些页、添加多少页。',missing:'请上传且仅上传一份需要修改的原始 .pptx，可另附其他格式的参考资料。',placeholder:'需要修改哪些页面或章节？添加什么内容、放在哪里？哪些内容或设计应保持不变？'},
 fr:{label:'Que souhaitez-vous faire ?',create:'Créer une présentation',edit:'Modifier ou compléter un PPT',createHelp:'Créez à partir du brief, de documents ou de recherches web. Les pièces jointes sont facultatives.',editHelp:'Joignez un seul PPTX original et, si besoin, des références. Décrivez les modifications ; les autres diapositives seront conservées.',pages:'Nombre de diapositives à créer',automatic:'Aucun nombre requis. Le brief détermine les diapositives à modifier ou à ajouter.',missing:'Joignez exactement un PPTX original à modifier. Les autres formats de référence sont acceptés.',placeholder:'Quelles diapositives modifier ? Que faut-il ajouter et conserver ?'},
 es:{label:'¿Qué quieres hacer?',create:'Crear una presentación',edit:'Editar o ampliar un PPT',createHelp:'Empieza con tu encargo, documentos o investigación web. Los archivos son opcionales.',editHelp:'Adjunta un único PPTX original y referencias opcionales. Describe los cambios; se conservarán las demás diapositivas.',pages:'Diapositivas de la nueva presentación',automatic:'No necesitas elegir una cantidad. El encargo determina qué modificar y cuánto añadir.',missing:'Adjunta exactamente un PPTX original para editar. Puedes añadir referencias en otros formatos.',placeholder:'¿Qué diapositivas hay que modificar? ¿Qué añadir y qué conservar?'},
 ja:{label:'何をしますか？',create:'PPTを新規作成',edit:'既存PPTを編集・拡張',createHelp:'依頼、参考資料、Web調査から新規作成します。資料の添付は任意です。',editHelp:'元のPPTXを1つ添付し、変更・追加内容を説明してください。対象外のページは保持します。参考資料も添付できます。',pages:'新しいPPTの目標枚数',automatic:'枚数の指定は不要です。依頼内容から編集対象と追加枚数を判断します。',missing:'編集する元のPPTXを1つだけ添付してください。他形式の参考資料も追加できます。',placeholder:'どのページを変更しますか？追加する内容と保持する内容を説明してください。'}
};
