'use client';
import ActivityTimeline from '@/app/activity-timeline';
import QueueStatus from '@/app/queue-status';
import CreationStory from '@/app/creation-story';
import {queueWords} from '@/lib/queue-i18n';
import type {QueueHealth} from '@/lib/queue-state';
import {taskModeMessages} from '@/lib/task-mode-i18n';
import {useEffect,useState} from 'react';
import {LanguagePicker,useLanguage} from '@/app/language';
import {displaySummary,languages,isLocale,type Locale} from '@/lib/i18n';
import type {Progress} from '@/lib/progress';
type Job={id:string;user_id:string;title:string;status:string;pages:number;language:string;created_at:number;updated_at:number;activity:Progress['events'][number]|null;previewCount:number;queuePosition:number|null};
type Detail=Job&{queue:QueueHealth|null;brief:string;style:string;summary:string|null;download:boolean;progress:Progress|null;attachments:{id:string;name:string}[]};
type Data={counts:Record<string,number>;jobs:Job[];page:number;limit:number;total:number;online:boolean;checkedAt:number;queue:QueueHealth};
const words:Record<Locale,string[]>={
 en:['Administration','Every request. One view.','Requests','Users','All statuses','Search title, brief, user or request ID','Request','User ID','Latest activity','Submitted','View request','Previous','Next','Select a request to inspect its brief, activity and previews.','Request details','Original brief','Last updated','Local worker online','Local worker offline','Refreshes every 5 seconds · Read-only','Unable to refresh. Displayed data may be out of date.','No matching requests.','Close details','No activity reported yet.','Back to studio','Page','Preview count','The worker has not reported recently. Progress may be interrupted.','Historical records contain user IDs, not email addresses.','Attachments','Access denied. Sign in with the administrator account.','Sign in'],
 'zh-CN':['管理后台','所有需求，一处掌握。','需求总数','用户数','全部状态','搜索标题、需求、用户或任务编号','需求','用户编号','最新进度','提交时间','查看需求','上一页','下一页','选择一个需求，查看完整内容、进度与预览。','需求详情','原始需求','最后更新','本地执行端在线','本地执行端离线','每 5 秒更新 · 只读管理','刷新失败，当前数据可能已过期。','暂无符合条件的需求。','关闭详情','尚无进度上报。','返回工作室','页','已预览页数','执行端近期未上报，进度可能已中断。','历史记录只保存用户编号，不包含邮箱。','附件','无访问权限，请用管理员账号登录。','登录'],
 fr:['Administration','Toutes les demandes, une seule vue.','Demandes','Utilisateurs','Tous les statuts','Rechercher un titre, un besoin ou un identifiant','Demande','Identifiant utilisateur','Dernière activité','Soumis le','Voir la demande','Précédent','Suivant','Sélectionnez une demande pour voir son contenu, son activité et ses aperçus.','Détails','Demande originale','Dernière mise à jour','Exécuteur local connecté','Exécuteur local déconnecté','Actualisation toutes les 5 secondes · Lecture seule','Actualisation impossible. Les données peuvent être périmées.','Aucune demande correspondante.','Fermer','Aucune activité signalée.','Retour au studio','Page','Aperçus','Aucun signal récent de l’exécuteur. La progression peut être interrompue.','Les anciens enregistrements contiennent des identifiants, sans adresses e-mail.','Pièces jointes','Accès refusé. Connectez-vous avec le compte administrateur.','Connexion'],
 es:['Administración','Todas las solicitudes, una sola vista.','Solicitudes','Usuarios','Todos los estados','Buscar título, solicitud o identificador','Solicitud','ID de usuario','Última actividad','Enviado','Ver solicitud','Anterior','Siguiente','Selecciona una solicitud para ver su contenido, actividad y vistas previas.','Detalles','Solicitud original','Última actualización','Ejecutor local conectado','Ejecutor local desconectado','Actualización cada 5 segundos · Solo lectura','No se puede actualizar. Los datos pueden estar desactualizados.','No hay solicitudes coincidentes.','Cerrar','Sin actividad registrada.','Volver al estudio','Página','Vistas previas','El ejecutor no ha informado recientemente. El progreso puede estar interrumpido.','Los registros históricos contienen identificadores, no correos electrónicos.','Archivos adjuntos','Acceso denegado. Inicia sesión con la cuenta de administrador.','Iniciar sesión'],
 ja:['管理画面','すべてのリクエストを、一か所で。','リクエスト','ユーザー','すべての状態','タイトル・依頼内容・ユーザーIDで検索','リクエスト','ユーザーID','最新の進捗','送信日時','詳細を見る','前へ','次へ','リクエストを選択すると、内容・進捗・プレビューを確認できます。','詳細','依頼内容','最終更新','ローカル実行端末はオンライン','ローカル実行端末はオフライン','5秒ごとに更新 · 閲覧専用','更新できません。表示内容が古い可能性があります。','該当するリクエストはありません。','閉じる','進捗はまだ報告されていません。','スタジオへ','ページ','プレビュー数','最近の応答がありません。処理が中断している可能性があります。','過去の記録にはユーザーIDのみが含まれ、メールアドレスはありません。','添付ファイル','アクセスできません。管理者アカウントでログインしてください。','ログイン']
};
export default function Dashboard(){
 const {locale,t}=useLanguage(),w=words[locale],qw=queueWords[locale];
 const m=taskModeMessages[locale];const scope=(pages:number)=>pages===0?m.edit:`${m.create} · ${pages} ${w[25]}`;
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(false),[denied,setDenied]=useState(false);
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<string|null>(null);
 const [detail,setDetail]=useState<Detail|null>(null),[detailError,setDetailError]=useState(false);
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setPage(1);},300);return()=>clearTimeout(timer);},[search]);
 useEffect(()=>{let active=true;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
  async function poll(){try{const response=await fetch(`/api/admin/jobs?${new URLSearchParams({q:query,status,page:String(page)})}`,{cache:'no-store',signal:controller.signal});if(response.status===401||response.status===403){if(active){setDenied(true);setData(null);setDetail(null);}return;}if(!response.ok)throw Error();const result=await response.json() as Data;if(active){setData(result);setError(false);}}
   catch{if(active)setError(true);}finally{if(active)timer=setTimeout(poll,5000);}}
  setData(null);void poll();return()=>{active=false;controller.abort();clearTimeout(timer);};
 },[query,status,page]);
 useEffect(()=>{setDetail(null);setDetailError(false);if(!selected)return;let active=true;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
  async function poll(){try{const response=await fetch(`/api/admin/jobs/${selected}`,{cache:'no-store',signal:controller.signal});if(response.status===401||response.status===403){if(active){setDenied(true);setData(null);setDetail(null);}return;}if(!response.ok)throw Error();const result=await response.json() as Detail;if(active){setDetail(result);setDetailError(false);}}
   catch{if(active)setDetailError(true);}finally{if(active)timer=setTimeout(poll,5000);}}
  void poll();return()=>{active=false;controller.abort();clearTimeout(timer);};
 },[selected]);
 const date=(value:number)=>new Date(value).toLocaleString(locale);
 const label=(value:string)=>Object.hasOwn(t.statuses,value)?t.statuses[value as keyof typeof t.statuses]:t.unknownStatus;
 const activity=(job:Job)=>['complete','failed','queued'].includes(job.status)?label(job.status):job.activity?(job.activity.detail||t.activities[job.activity.code]):w[23];
 if(denied)return <main className="admin"><h1>{w[30]}</h1><a href="/signin-with-chatgpt?return_to=/admin">{w[31]} →</a></main>;
 return <main className="admin"><header><a className="brand" href="/">PPTX LAB <span>/ {w[0]}</span></a><div className="header-actions"><a href="/">{w[24]} ↗</a><LanguagePicker/></div></header>
 <section className="admin-intro"><div><p className="eyebrow">RICK’S CONTROL ROOM</p><h1>{w[1]}</h1><p>{w[19]}</p></div><div className={`worker-indicator ${data?.online?'online':''}`}>{data?(data.online?w[17]:w[18]):t.loading}{data&&<small>{date(data.checkedAt)}</small>}</div></section>
 {data&&<QueueStatus queue={data.queue}/>}
 <section className="admin-counts" aria-label={w[0]}>{[['total',w[2]],['users',w[3]],['queued',t.statuses.queued],['running',t.statuses.running],['complete',t.statuses.complete],['failed',t.statuses.failed]].map(([key,title])=><article key={key}><span>{title}</span><strong>{data?.counts[key]??'—'}</strong></article>)}</section>
 <div className="admin-filters"><label><span>{w[5]}</span><input type="search" value={search} maxLength={200} onChange={e=>setSearch(e.target.value)} placeholder={w[5]}/></label><label><span>{w[4]}</span><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">{w[4]}</option>{['queued','running','complete','failed'].map(s=><option value={s} key={s}>{label(s)}</option>)}</select></label></div>
 {error&&<p role="alert" className="error">{w[20]}</p>}<p className="fineprint">{w[28]}</p>
 <div className="admin-columns"><section aria-label={w[2]}><div className="admin-table-wrap"><table><thead><tr>{[w[6],w[7],w[8],w[9]].map(x=><th key={x} scope="col">{x}</th>)}</tr></thead><tbody>{data?.jobs.map(job=><tr key={job.id} className={selected===job.id?'selected':''}><td><button className="request-title" onClick={()=>setSelected(job.id)} aria-label={`${w[10]}: ${job.title}`} aria-pressed={selected===job.id}>{job.title}</button><small>{scope(job.pages)} · {isLocale(job.language)?languages[job.language]:'—'}</small></td><td><button className="user-id" title={job.user_id} onClick={()=>setSearch(job.user_id)}>{job.user_id}</button></td><td><span className={`status status-${job.status}`}>{label(job.status)}</span><small>{activity(job)}</small>{job.queuePosition!==null&&<small>{qw.position} #{job.queuePosition} · {qw.waited} {Math.max(0,Math.floor(((data?.checkedAt??job.created_at)-job.created_at)/60000))} {qw.minutes}</small>}{job.previewCount>0&&<small>{t.previews}: {job.previewCount}{job.pages>0?`/${job.pages}`:''}</small>}</td><td><time>{date(job.created_at)}</time></td></tr>)}</tbody></table></div>{!data?<p role="status">{t.loading}</p>:!data.jobs.length?<p>{w[21]}</p>:null}
 <nav className="admin-pagination" aria-label={w[25]}><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>{w[11]}</button><span>{page} / {Math.max(1,Math.ceil((data?.total||0)/25))} · {data?.total??'—'} {w[2]}</span><button disabled={!data||page*25>=data.total} onClick={()=>setPage(p=>p+1)}>{w[12]}</button></nav></section>
 <aside className="admin-detail" aria-label={w[14]}>{!selected?<p className="empty-detail">{w[13]}</p>:<><button className="admin-close" onClick={()=>setSelected(null)}>{w[22]} ×</button>{detailError&&<p className="error" role="alert">{w[20]}</p>}{!detail?<p>{t.loading}</p>:<><p className="eyebrow">{w[14]}</p><h2>{detail.title}</h2><span className={`status status-${detail.status}`}>{label(detail.status)}</span><dl><dt>{w[7]}</dt><dd>{detail.user_id}</dd><dt>ID</dt><dd>{detail.id}</dd><dt>{w[9]}</dt><dd>{date(detail.created_at)}</dd><dt>{w[16]}</dt><dd>{date(detail.updated_at)}</dd><dt>{m.label} / {t.pptLanguage}</dt><dd>{scope(detail.pages)} / {isLocale(detail.language)?languages[detail.language]:'—'}</dd><dt>{t.style}</dt><dd>{detail.style}</dd></dl>{detail.pages===0&&<p className="fineprint">{m.automatic}</p>}
 {detail.queue&&<QueueStatus queue={detail.queue} position={detail.queuePosition} createdAt={detail.created_at}/>}
 {detail.status==='running'&&Date.now()-detail.updated_at>120000&&<p className="error">{w[27]}</p>}
 <h3>{w[15]}</h3><p className="original-brief">{detail.brief}</p>{!!detail.attachments.length&&<><h3>{w[29]}</h3><ul>{detail.attachments.map(a=><li key={a.id}>{a.name}</li>)}</ul></>}
 {detail.summary&&<p>{displaySummary(detail.summary,t)}</p>}<p><a className="admin-link" href={`/jobs/${detail.id}`}>{t.details} →</a></p><p><a className="admin-link" href={`/admin/jobs/${detail.id}/trace`}>执行记录 · 命令、输出与审核 →</a></p><CreationStory key={detail.id} progress={detail.progress} pages={detail.pages} status={detail.status} base={`/api/admin/jobs/${detail.id}`}/>
 {!!detail.progress?.events.length&&<details><summary>{w[8]} · {detail.progress.events.length}</summary><ActivityTimeline events={detail.progress.events}/></details>}
 {detail.download&&<a className="admin-link" href={`/api/admin/jobs/${detail.id}/download`}>{t.download} ↓</a>}</>}</>}</aside></div><footer><span>PPTX LAB / PRIVATE ADMINISTRATION</span><span>{w[19]}</span></footer></main>;
}
