import {useEffect,useRef,useState} from 'react';
import * as maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import type {FeaturePack,FeatureProps} from '../types';
import {emitFeature,featureError,boundedNumber,packURL} from '../types';
import {readBounded} from '../fetch';
export function mapResource(value:string,base:string,allowlist:string[]){const url=new URL(value,base);if(url.username||url.password||!['https:','http:'].includes(url.protocol)||url.origin!==new URL(base).origin&&(url.protocol!=='https:'||!allowlist.includes(url.origin)))throw new Error(`Map request origin denied: ${url.origin}`);return url.href;}
const instances=new WeakMap<object,Map<string,maplibregl.Map>>();function registry(runtime:object){let map=instances.get(runtime);if(!map){map=new Map();instances.set(runtime,map);}return map;}
export function AdvancedMap({p,runtime,nodeId}:FeatureProps){const host=useRef<HTMLDivElement>(null),current=useRef(p),mapRef=useRef<maplibregl.Map|undefined>(undefined);current.current=p;const [error,setError]=useState('');
 useEffect(()=>{if(!host.current)return;let live=true;const abort=new AbortController();let map:maplibregl.Map|undefined;let resize:ResizeObserver|undefined;
  const initialize=async()=>{const allowlist=runtime.scene.runtimeOptions?.networkAllowlist??[];let geojson=p.geojson??{type:'FeatureCollection',features:[]};if(p.src){const response=await fetch(runtime.assets.resolve(p.src),{redirect:'error',credentials:'omit',signal:abort.signal});geojson=JSON.parse(new TextDecoder().decode(await readBounded(response,16*1024*1024)));}if(!live)return;
   const style:any=p.style??{version:8,sources:{local:{type:'geojson',data:geojson}},layers:[{id:'background',type:'background',paint:{'background-color':p.background??'#eef6ff'}},{id:'areas',type:'fill',source:'local',filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':p.fill??'#38bdf8','fill-opacity':0.55}},{id:'lines',type:'line',source:'local',filter:['==',['geometry-type'],'LineString'],paint:{'line-color':p.stroke??'#0369a1','line-width':3}},{id:'points',type:'circle',source:'local',filter:['==',['geometry-type'],'Point'],paint:{'circle-color':p.pointColor??'#fb7185','circle-radius':7,'circle-stroke-width':2,'circle-stroke-color':'#ffffff'}}]};
   maplibregl.setWorkerUrl(packURL('map/maplibre-gl-worker.mjs'));maplibregl.setWorkerCount(1);map=new maplibregl.Map({container:host.current!,style,center:p.center??[0,0],zoom:boundedNumber(p.zoom,1,0,22),pitch:boundedNumber(p.pitch,0,0,85),attributionControl:false,transformRequest:url=>({url:mapResource(url,runtime.base,allowlist),credentials:'same-origin'}),maxTileCacheSize:128});mapRef.current=map;registry(runtime).set(nodeId,map);map.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-right');
   map.on('load',()=>emitFeature(runtime,nodeId,'mapReady',{center:map!.getCenter().toArray(),zoom:map!.getZoom()}));map.on('error',event=>{if(live)setError(event.error.message);});map.on('moveend',()=>{const value={center:map!.getCenter().toArray(),zoom:map!.getZoom()};if(current.current.viewPath)runtime.store.set(current.current.viewPath,value);emitFeature(runtime,nodeId,'mapMove',value);});map.on('click',event=>{const features=map!.queryRenderedFeatures(event.point).filter(value=>value.layer.type!=='background');const value={lng:event.lngLat.lng,lat:event.lngLat.lat,features:features.slice(0,50).map(feature=>({id:feature.id,properties:feature.properties,geometry:feature.geometry}))};if(current.current.selectionPath)runtime.store.set(current.current.selectionPath,value);emitFeature(runtime,nodeId,'mapSelect',value);});resize=new ResizeObserver(()=>map!.resize());resize.observe(host.current!);
  };void initialize().catch(error=>{if(live&&!abort.signal.aborted)setError(featureError(error));});return()=>{live=false;abort.abort();resize?.disconnect();registry(runtime).delete(nodeId);map?.remove();mapRef.current=undefined;};
 },[runtime,nodeId,p.src]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;if(p.geojson){const source=map.getSource('local') as maplibregl.GeoJSONSource|undefined;source?.setData(p.geojson);}if(p.center||p.zoom!==undefined)map.jumpTo({center:p.center,zoom:p.zoom});},[p.geojson,p.center,p.zoom]);
 return <div style={{position:'relative',height:'100%',width:'100%'}}><div aria-label={p.ariaLabel??'Interactive map'} ref={host} style={{width:'100%',height:'100%'}}/>{error&&<div role="alert" style={{position:'absolute',top:0,left:0,right:0,background:'#fff',color:'#b91c1c',padding:8}}>Map unavailable: {error}</div>}</div>;
}
const pack:FeaturePack={id:'map',install(context){context.component('AdvancedMap',AdvancedMap);context.action('map.flyTo',args=>{const map=registry(context.runtime).get(args.target);if(!map)throw new Error('Map component not mounted');map.flyTo({center:args.center,zoom:args.zoom,pitch:args.pitch,bearing:args.bearing,duration:boundedNumber(args.duration,800,0,30000),essential:false});});}};export default pack;
