import {createRoot} from 'react-dom/client';
import {Runtime} from '../core/runtime';
import {loadFeaturePacks} from '../feature-packs';
import {SceneRoot,RuntimeErrorBoundary} from '../renderer/SceneRoot';
import {identity,capabilities} from '../office/settings';
import {digest,safeRelative} from '../core/assets';
import './style.css';
import {diagnosticOf} from '../core/diagnostics';
declare global{interface Window{__interactive:any}}
async function start(){const office=await identity(),query=new URLSearchParams(location.search),deck=office?.deckId??query.get('deck'),scene=office?.sceneId??query.get('scene');let path=query.get('spec'),expected=office?.specHash,base=new URL('./deck/',location.href).href;if(deck){safeRelative(deck);const response=await fetch(`/decks/${deck}/bundle.json`);if(!response.ok)throw new Error('Deck bundle unavailable');const manifest=await response.json(),record=manifest.scenes[scene!];if(!record)throw new Error('Scene not in bundle');base=new URL(`/decks/${deck}/`,location.href).href;path=new URL(safeRelative(record.path),base).href;expected=expected??record.sha256;if(office&&record.sha256!==office.specHash)throw new Error('Content identity differs from bundle');}if(!path){document.getElementById('root')!.textContent='Open a scene with ?spec=scene.json, or run pptx interactive preview scene.json.';return;}if(!deck){const url=new URL(path,location.href);if(url.origin!==location.origin)throw new Error('Scene must be same-origin');path=url.href;base=new URL('./',url).href;}const response=await fetch(path,{redirect:'error'});if(!response.ok)throw new Error('Scene unavailable');const bytes=await response.arrayBuffer();if(expected&&await digest(bytes)!==expected)throw new Error('Scene hash mismatch');const runtime=new Runtime(JSON.parse(new TextDecoder().decode(bytes)),base);await loadFeaturePacks(runtime);await runtime.initialize();window.__interactive={runtime,ready:true,capabilities:capabilities(),identity:office,snapshot:()=>runtime.store.snapshot(),restore:(v:any)=>runtime.store.restore(v),dispatch:(a:any)=>runtime.dispatch(a),seek:(id:string,time:number)=>runtime.timeline.seek(id,time),testPlan:runtime.scene.testPlan??[]};createRoot(document.getElementById('root')!).render(<RuntimeErrorBoundary debug={runtime.scene.runtimeOptions?.debug} sceneId={runtime.scene.id}><SceneRoot runtime={runtime}/></RuntimeErrorBoundary>);window.addEventListener('pagehide',()=>runtime.dispose(),{once:true});}
start().catch(error=>{window.__interactive={ready:false,error:String(error),diagnostic:diagnosticOf(error,{phase:'boot'})};const root=document.getElementById('root')!;root.replaceChildren();const p=document.createElement('p');p.setAttribute('role','alert');p.textContent='Interactive content unavailable. Static slide content remains available.';root.append(p);if(new URLSearchParams(location.search).has('debug')){const pre=document.createElement('pre');pre.textContent=JSON.stringify(window.__interactive.diagnostic,null,2);root.append(pre);}console.error(error);});
