import {test,expect,type Page,type BrowserContext} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {createHash} from 'node:crypto';

const baseScene=(requires:string[],nodes:any[],extra:any={})=>({schemaVersion:1,id:'pack-smoke',viewport:{width:1000,height:650},initialState:{},requires:['core',...requires],nodes,...extra});
const node=(component:string,props:any={}):any=>({id:'demo',type:'component',component,props:{x:20,y:20,width:940,height:580,...props}});
async function prepare(context:BrowserContext,page:Page,scene:any,files:Record<string,{body:Buffer|string;type:string}>={}){
 await context.route('**/packs/**',async route=>{const url=new URL(route.request().url());if(url.port==='41977')return route.continue();const pathname=url.pathname;const relative=pathname.replace(/^\/packs\//,'');if(relative.includes('..'))return route.abort();try{const body=await readFile(resolve('dist/packs',relative));const extension=extname(pathname);const contentType=extension==='.js'||extension==='.mjs'?'text/javascript':extension==='.json'?'application/json':extension==='.wasm'?'application/wasm':'application/octet-stream';const headers:Record<string,string>={};if(pathname.endsWith('/code-runner.worker.js'))headers['Content-Security-Policy']="default-src 'none'; script-src 'self' 'unsafe-eval' 'wasm-unsafe-eval'; connect-src 'self'; worker-src 'none'";await route.fulfill({body,contentType,headers});}catch{await route.fulfill({status:404,body:'Missing test pack asset'});}});
 await context.route('**/pack-smoke.scene.json',route=>route.fulfill({json:scene}));for(const [name,value]of Object.entries(files))await context.route(`**/${name}`,route=>route.fulfill({body:value.body,contentType:value.type}));
 await page.goto('/preview.html?spec=pack-smoke.scene.json&debug=1');await page.waitForFunction(()=>!!window.__interactive);const initial=await page.evaluate(()=>({ready:window.__interactive.ready,error:window.__interactive.error}));expect(initial,initial.error).toMatchObject({ready:true});
}
async function action(page:Page,name:string,args:any={}){return page.evaluate(({name,args})=>window.__interactive.dispatch([{type:'plugin',name,target:'demo',args}]),{name,args});}
async function state(page:Page,path:string){return page.evaluate(path=>window.__interactive.runtime.store.get(path),path);}

test('a core-only scene requests no optional pack chunk or WASM',async({page,context})=>{
 const manifest=JSON.parse(await readFile('dist/.vite/manifest.json','utf8'));const heavy=new Set(Object.entries(manifest).filter(([key])=>/src\/feature-packs\/(code|three|ml|map|math)\//.test(key)).map(([,entry]:any)=>'/'+entry.file));const requests:string[]=[];page.on('request',request=>requests.push(new URL(request.url()).pathname));await prepare(context,page,baseScene([],[{id:'label',type:'Text',props:{text:'Core alone',width:400,height:100}}]));await expect(page.getByText('Core alone')).toBeVisible();expect(requests.filter(path=>heavy.has(path)||/\/packs\/|\.wasm$|\/src\/feature-packs\/(code|three|ml|map|math)\//.test(path))).toEqual([]);
});

test('Monaco JS executes input, resets, stops infinite loops and denies network',async({page,context})=>{
 await prepare(context,page,baseScene(['code'],[node('CodeEditor',{code:'console.log(input()); return 7;',stdin:['hello'],timeoutMs:250,resultPath:'result'})]));await expect(page.locator('.monaco-editor')).toBeVisible();await action(page,'code.run');expect(await state(page,'result')).toMatchObject({status:'done',stdout:'hello\n',result:7});
 await action(page,'code.setCode',{code:'while (true) {}'});await action(page,'code.run');expect(await state(page,'result')).toMatchObject({status:'timed_out'});
 await action(page,'code.setCode',{code:'await fetch("https://example.com/denied");'});await action(page,'code.run');const denied=await state(page,'result');expect(denied.status).toBe('error');expect(denied.stderr).toContain('Network');
 await action(page,'code.setCode',{code:'await import("https://example.com/denied.js");'});await action(page,'code.run');expect((await state(page,'result')).status).toBe('error');
 await action(page,'code.setCode',{code:'await new Promise(resolve => setTimeout(resolve, 10000));'});const running=action(page,'code.run');await expect(page.locator('[data-code-status]')).toHaveAttribute('data-code-status','running');await action(page,'code.stop');await running;expect((await state(page,'result')).status).toBe('stopped');
 await action(page,'code.reset');expect(await state(page,'result')).toBeNull();expect(await page.evaluate(()=>window.__interactive.dispatch([{type:'plugin',name:'code.getCode',target:'demo',result:'source'}]).then(()=>window.__interactive.runtime.store.get('source')))).toBe('console.log(input()); return 7;');
});
test('Python uses local Pyodide and stdin/stdout in a bounded worker',async({page,context})=>{
 test.setTimeout(100000);await prepare(context,page,baseScene(['code'],[node('CodeEditor',{language:'python',code:'print("python local")\nprint(int(input()) + 1)\n2 + 2',stdin:['41'],timeoutMs:3000,resultPath:'result'})]));await expect(page.locator('.monaco-editor')).toBeVisible();await action(page,'code.run');const result=await state(page,'result');expect(result,result?.stderr).toMatchObject({status:'done',result:4});expect(result.stdout).toContain('python local\n42\n');
 await action(page,'code.setCode',{code:'from js import fetch\nawait fetch("https://example.com/denied")'});await action(page,'code.run');expect((await state(page,'result')).status).toBe('error');
});

function glbTriangle(){const positions=Buffer.from(new Float32Array([-1,-1,0,1,-1,0,0,1,0]).buffer);const model={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{name:'triangle',mesh:0}],meshes:[{primitives:[{attributes:{POSITION:0}}]}],buffers:[{byteLength:positions.length}],bufferViews:[{buffer:0,byteOffset:0,byteLength:positions.length,target:34962}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[-1,-1,0],max:[1,1,0]}]};let json=Buffer.from(JSON.stringify(model));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);const header=Buffer.alloc(20);header.writeUInt32LE(0x46546c67,0);header.writeUInt32LE(2,4);header.writeUInt32LE(12+8+json.length+8+positions.length,8);header.writeUInt32LE(json.length,12);header.writeUInt32LE(0x4e4f534a,16);const bin=Buffer.alloc(8);bin.writeUInt32LE(positions.length,0);bin.writeUInt32LE(0x004e4942,4);return Buffer.concat([header,json,bin,positions]);}
test('Three loads a real GLB, raycasts and binds object visibility',async({page,context})=>{
 const model=glbTriangle();const sceneNode=node('ThreeScene',{src:'triangle.glb',camera:{position:[0,0,3],target:[0,0,0]},selectionPath:'selected'});sceneNode.bind={visibility:{expr:'state.visibility'}};await prepare(context,page,baseScene(['three'],[sceneNode],{assets:{model:{path:'triangle.glb',bytes:model.length,sha256:createHash('sha256').update(model).digest('hex')}},interactions:[{target:'demo',event:'threeReady',actions:[{type:'set',path:'modelReady',value:true}]}]}),{'triangle.glb':{body:model,type:'model/gltf-binary'}});await expect.poll(()=>state(page,'modelReady')).toBe(true);const canvas=page.locator('[data-feature=ThreeScene] canvas');await expect(canvas).toBeVisible();await canvas.click();await expect.poll(()=>state(page,'selected')).toBe('triangle');await action(page,'three.camera',{position:[1,1,4],target:[0,0,0],duration:50});await page.waitForTimeout(100);await page.evaluate(()=>window.__interactive.dispatch([{type:'plugin',name:'three.inspect',target:'demo',result:'view'}]));expect((await state(page,'view')).camera.position[0]).toBeCloseTo(1);await page.evaluate(()=>window.__interactive.runtime.store.set('visibility',{triangle:false}));await page.waitForTimeout(50);await page.evaluate(()=>window.__interactive.dispatch([{type:'plugin',name:'three.inspect',target:'demo',result:'view'}]));expect((await state(page,'view')).objects.find((item:any)=>item.name==='triangle').visible).toBe(false);await expect(page.getByRole('alert')).toHaveCount(0);
});

const varint=(n:number)=>{const out:number[]=[];do{let byte=n&127;n=Math.floor(n/128);if(n)byte|=128;out.push(byte);}while(n);return Buffer.from(out);};
const field=(id:number,bytes:Buffer|string)=>{const value=typeof bytes==='string'?Buffer.from(bytes):bytes;return Buffer.concat([varint(id*8+2),varint(value.length),value]);};
const integer=(id:number,n:number)=>Buffer.concat([varint(id*8),varint(n)]);
function identityModel(){const shape=Buffer.concat([field(1,integer(1,1)),field(1,integer(1,2))]);const type=field(1,Buffer.concat([integer(1,1),field(2,shape)]));const input=field(11,Buffer.concat([field(1,'x'),field(2,type)])),output=field(12,Buffer.concat([field(1,'y'),field(2,type)]));const node=field(1,Buffer.concat([field(1,'x'),field(2,'y'),field(4,'Identity')]));const graph=field(7,Buffer.concat([node,field(2,'smoke'),input,output]));return Buffer.concat([integer(1,9),field(2,'interactive-runtime-tests'),graph,field(8,integer(2,13))]);}
test('ONNX runs an actual generic identity model with local WASM fallback',async({page,context})=>{
 test.setTimeout(100000);const bytes=identityModel();await prepare(context,page,baseScene(['ml'],[node('ModelRunner',{model:'identity.onnx',inputs:{x:{type:'float32',dims:[1,2],data:[3,7]}},preferWebGPU:false,resultPath:'result'})]),{'identity.onnx':{body:bytes,type:'application/octet-stream'}});await expect(page.locator('[data-model-status]')).toHaveAttribute('data-model-status','ready',{timeout:65000});await action(page,'ml.run');expect(await state(page,'result')).toEqual({y:{type:'float32',dims:[1,2],data:[3,7]}});await expect(page.locator('[data-model-status]')).toContainText('wasm');
});
test('MapLibre renders local GeoJSON and reports click selection',async({page,context})=>{
 await prepare(context,page,baseScene(['map'],[node('AdvancedMap',{geojson:{type:'FeatureCollection',features:[{type:'Feature',properties:{name:'local-point'},geometry:{type:'Point',coordinates:[0,0]}}]},center:[0,0],zoom:2,selectionPath:'selection'})],{interactions:[{target:'demo',event:'mapReady',actions:[{type:'set',path:'ready',value:true}]}]}));await expect.poll(()=>state(page,'ready')).toBe(true);await page.locator('.maplibregl-canvas').click();await expect.poll(async()=>((await state(page,'selection'))?.features??[]).length).toBeGreaterThan(0);await expect(page.getByRole('alert')).toHaveCount(0);
});
test('KaTeX updates from state and approved plugin functions initialize derived state',async({page,context})=>{
 const source='export default {id:"lesson",version:"1.0.0",functions:{double:x=>x*2}};';const math=node('Math',{displayMode:true});math.bind={tex:{expr:'state.tex'}} as any;await prepare(context,page,baseScene(['math'],[math],{initialState:{tex:'x^2+1',n:3},derivedState:{answer:{expr:'lesson_double(state.n)'}},plugins:[{id:'lesson',version:'1.0.0',path:'lesson.js',sha256:createHash('sha256').update(source).digest('hex'),capabilities:['functions']}],runtimeOptions:{allowedPlugins:['lesson']}}),{'lesson.js':{body:source,type:'text/javascript'}});expect(await state(page,'answer')).toBe(6);await expect(page.locator('.katex')).toHaveCount(1);await page.evaluate(()=>window.__interactive.runtime.store.set('tex','\\frac{a}{b}'));await expect(page.locator('[role=math]')).toContainText('ab');
});
