import {useEffect,useRef,useState} from 'react';
import type {FeaturePack,FeatureProps} from '../types';
import {emitFeature,featureError} from '../types';
import {ModelSession,AdapterRegistry} from './runner';
import {yoloAdapter} from './yolo-adapter';
import type {ModelAdapter} from './contracts';
import {readBounded} from '../fetch';
type Controller={run:(input?:any)=>Promise<any>;stop:()=>void;load:()=>Promise<void>};type Registry={controllers:Map<string,Controller>;adapters:AdapterRegistry};const registries=new WeakMap<object,Registry>();
function registry(runtime:object){let value=registries.get(runtime);if(!value){value={controllers:new Map(),adapters:new AdapterRegistry()};value.adapters.register('yolo',yoloAdapter);registries.set(runtime,value);}return value;}
export function registerModelAdapter(runtime:object,name:string,adapter:ModelAdapter){registry(runtime).adapters.register(name,adapter);}
export function ModelRunner({p,runtime,nodeId}:FeatureProps){const current=useRef(p);current.current=p;const [status,setStatus]=useState('idle'),[detail,setDetail]=useState(''),[result,setResult]=useState<any>(null);
 useEffect(()=>{let live=true;const abort=new AbortController();const model=new ModelSession();let loading:Promise<void>|undefined;const set=(value:string,text='')=>{if(live){setStatus(value);setDetail(text);}};
  const load=()=>loading??=(async()=>{set('loading');try{const source=current.current.model??current.current.src;if(!source)throw new Error('ModelRunner requires model asset');const response=await fetch(runtime.assets.resolve(source),{signal:abort.signal,credentials:'omit',redirect:'error'});const bytes=await readBounded(response,256*1024*1024);const info=await model.load(bytes,current.current.preferWebGPU!==false);set('ready',info.provider);emitFeature(runtime,nodeId,'modelReady',info);}catch(error){set('error',featureError(error));throw error;}finally{loading=undefined;}})();
  const controller:Controller={load,stop:()=>{model.stop();set('stopped');},run:async input=>{if(!model.loaded)await load();set('running',model.provider);const props=current.current;try{const adapter=registry(runtime).adapters.get(props.adapter??'tensors'),inputs=await adapter.preprocess(input??props.inputs,props.adapterOptions??{});const inference=await model.run(inputs,props.timeoutMs),value=await adapter.postprocess(inference.outputs,props.adapterOptions??{});if(live){setResult(value);set('done',inference.provider);if(props.resultPath)runtime.store.set(props.resultPath,value);emitFeature(runtime,nodeId,'modelResult',{provider:inference.provider,result:value});}return value;}catch(error){set('error',featureError(error));throw error;}}};registry(runtime).controllers.set(nodeId,controller);if(p.autoLoad!==false)void load().catch(()=>{});return()=>{live=false;abort.abort();model.stop();registry(runtime).controllers.delete(nodeId);};
 },[runtime,nodeId,p.model,p.src]);
 return <div style={{boxSizing:'border-box',height:'100%',padding:12,fontFamily:'system-ui',background:p.background??'#f1f5f9',border:'1px solid #cbd5e1',borderRadius:8,overflow:'auto'}}><div style={{display:'flex',gap:8,alignItems:'center'}}><button onClick={()=>void registry(runtime).controllers.get(nodeId)?.run().catch(()=>{})} disabled={status==='running'}>Run model</button><button onClick={()=>registry(runtime).controllers.get(nodeId)?.stop()}>Stop</button><span role="status" data-model-status={status}>{status} {detail}</span></div>{status==='error'&&<p role="alert">{detail}</p>}{result!==null&&<pre aria-label="Model output" style={{whiteSpace:'pre-wrap',fontSize:p.fontSize??12}}>{JSON.stringify(result,null,2).slice(0,50000)}</pre>}</div>;
}
const pack:FeaturePack={id:'ml',install(context){context.component('ModelRunner',ModelRunner);context.action('ml.run',args=>{const controller=registry(context.runtime).controllers.get(args.target);if(!controller)throw new Error('ModelRunner not mounted');return controller.run(args.inputs);});for(const action of ['load','stop'] as const)context.action(`ml.${action}`,args=>{const controller=registry(context.runtime).controllers.get(args.target);if(!controller)throw new Error('ModelRunner not mounted');return controller[action]();});context.dispose(()=>{registry(context.runtime).controllers.forEach(controller=>controller.stop());registries.delete(context.runtime);});}};export default pack;
