import {validateTensors,type ModelAdapter,type TensorMap} from './contracts';
export type Detection={box:[number,number,number,number];score:number;classId:number};
export function intersectionOverUnion(a:number[],b:number[]){const area=(box:number[])=>Math.max(0,box[2]-box[0])*Math.max(0,box[3]-box[1]);const intersection=area([Math.max(a[0],b[0]),Math.max(a[1],b[1]),Math.min(a[2],b[2]),Math.min(a[3],b[3])]);return intersection/(area(a)+area(b)-intersection||1);}
export function nonMaximumSuppression(detections:Detection[],threshold=0.45,maximum=100){if(detections.length>30000)throw new Error('Too many candidate detections');if(!Number.isFinite(threshold)||threshold<0||threshold>1||!Number.isInteger(maximum)||maximum<1||maximum>1000||detections.some(v=>!Number.isFinite(v.score)||v.box.length!==4||v.box.some(x=>!Number.isFinite(x))||!Number.isInteger(v.classId)||v.classId<0))throw new Error('Invalid NMS options/candidates');const sorted=[...detections].sort((a,b)=>b.score-a.score),selected:Detection[]=[];for(const candidate of sorted){if(selected.every(existing=>existing.classId!==candidate.classId||intersectionOverUnion(existing.box,candidate.box)<=threshold)){selected.push(candidate);if(selected.length>=maximum)break;}}return selected;}
/** Example adapter for raw YOLOv8/YOLO11 [1, 4+classes, candidates] outputs. */
export const yoloAdapter:ModelAdapter={
 preprocess(value,options){const width=Number(options.width??640),height=Number(options.height??640);if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width*height>4*1024*1024||!Array.isArray(value.rgba)||value.rgba.length!==width*height*4)throw new Error('YOLO adapter needs RGBA pixels resized to the declared width/height');const data=new Array(width*height*3);for(let i=0;i<width*height;i++)for(let c=0;c<3;c++){const pixel=Number(value.rgba[i*4+c]);if(!Number.isFinite(pixel)||pixel<0||pixel>255)throw new Error('Invalid RGBA pixel value');data[c*width*height+i]=pixel/255;}return {[options.inputName??'images']:{type:'float32',dims:[1,3,height,width],data}};},
 postprocess(outputs:TensorMap,options){validateTensors(outputs);const tensor=outputs[options.outputName??Object.keys(outputs)[0]];if(tensor?.dims.length!==3||tensor.dims[0]!==1||tensor.dims[1]<5||tensor.dims[2]>30000)throw new Error('YOLO example expects [1,4+classes,candidates] output');const count=tensor.dims[2],classes=tensor.dims[1]-4,threshold=Number(options.confidence??0.25),candidates:Detection[]=[];for(let i=0;i<count;i++){let score=0,classId=0;for(let c=0;c<classes;c++){const value=Number(tensor.data[(c+4)*count+i]);if(value>score){score=value;classId=c;}}if(score<threshold)continue;const x=Number(tensor.data[i]),y=Number(tensor.data[count+i]),w=Number(tensor.data[count*2+i]),h=Number(tensor.data[count*3+i]);candidates.push({box:[x-w/2,y-h/2,x+w/2,y+h/2],score,classId});}return nonMaximumSuppression(candidates,Number(options.iouThreshold??0.45),Math.min(500,Number(options.maxDetections??100)));}
};
