'use client';
import {useEffect,useRef,useState} from 'react';
import {useLanguage} from '@/app/language';
import {validFiles,extensions} from '@/lib/attachments';
import type {Message} from '@/lib/conversation';
type Snapshot={messages:Message[];recovery:null|{resumable:boolean;revision:number;lastMessageSeq:number;updatedAt:number;phase:string};versions:{id:string;revision:number;created_at:number;pptx:number;bundle:number}[]};
const words={
 en:['Work with Codex','Ask a question or change the presentation as it is made.','Change request','Chat','Your message…','Attach files','Send','Sending','Saved','Received by Codex','Applied','You','No messages yet. Add context or ask a question.','Connection lost. Retrying…','Could not send. Retry safely.','Up to 3 files, 10 MB each, 20 MB total.','Resume from checkpoint','Resume to work on the latest messages. Earlier versions remain available.','Checkpoint saved','Versions','Interactive bundle','Remove','Could not resume. Refresh and retry.','Message saved; waiting for the worker.','Files upload with the message.','Only the latest 200 messages are shown.'],
 'zh-CN':['和 Codex 一起制作','制作过程中，可以随时补充要求、提问或上传文件。','修改要求','普通聊天','输入你的意见或问题…','添加附件','发送','正在发送','已保存','Codex 已收到','已应用','你','还没有消息。可以补充背景、提出修改或问个问题。','连接中断，正在重连…','发送未确认，可安全重试。','最多 3 个文件，每个 10 MB，合计 20 MB。','从断点继续','继续制作即可处理新消息，此前版本仍然保留。','恢复点已保存','历史版本','交互演示包','移除','未能恢复，请刷新后重试。','消息已保存，等待执行端接收。','附件随消息一起上传。','此处显示最近 200 条消息。'],
 fr:['Travailler avec Codex','Posez une question ou modifiez la présentation pendant sa création.','Modification','Discussion','Votre message…','Joindre des fichiers','Envoyer','Envoi','Enregistré','Reçu par Codex','Appliqué','Vous','Ajoutez du contexte ou posez une question.','Connexion interrompue. Nouvel essai…','Envoi non confirmé. Réessayez.','3 fichiers, 10 Mo chacun, 20 Mo au total.','Reprendre au point sauvegardé','Reprenez pour traiter les nouveaux messages. Les versions précédentes sont conservées.','Point de reprise enregistré','Versions','Dossier interactif','Retirer','Reprise impossible. Actualisez puis réessayez.','Message enregistré, en attente du service.','Les fichiers sont envoyés avec le message.','Les 200 derniers messages sont affichés.'],
 es:['Trabajar con Codex','Pregunta o cambia la presentación mientras se crea.','Solicitar cambios','Conversar','Tu mensaje…','Adjuntar archivos','Enviar','Enviando','Guardado','Recibido por Codex','Aplicado','Tú','Añade contexto o haz una pregunta.','Conexión interrumpida. Reintentando…','Envío sin confirmar. Reintenta.','3 archivos, 10 MB cada uno, 20 MB en total.','Continuar desde el punto guardado','Continúa para procesar los mensajes nuevos. Se conservan las versiones anteriores.','Punto guardado','Versiones','Paquete interactivo','Quitar','No se pudo continuar. Actualiza y reintenta.','Mensaje guardado, esperando al servicio.','Los archivos se envían con el mensaje.','Se muestran los últimos 200 mensajes.'],
 ja:['Codex と一緒に作成','作成中に質問、変更依頼、ファイル追加ができます。','変更依頼','チャット','メッセージを入力…','ファイル添付','送信','送信中','保存済み','Codex が受信','反映済み','あなた','背景情報を追加したり質問してください。','再接続中…','送信を確認できません。再試行できます。','3ファイルまで、各10 MB、合計20 MB。','保存地点から再開','新しいメッセージを処理するため再開します。以前の版は保持されます。','再開地点を保存済み','過去の版','インタラクティブ資料','削除','再開できません。更新して再試行してください。','保存済み。実行側の受信待ちです。','ファイルはメッセージとともに送信されます。','最新200件を表示しています。'],
};
export default function Conversation({id,status,updatedAt,onResume}:{id:string;status:string;updatedAt:number;onResume:()=>void}){
 const {locale}=useLanguage(),w=words[locale];const [data,setData]=useState<Snapshot>({messages:[],recovery:null,versions:[]});
 const [text,setText]=useState(''),[kind,setKind]=useState<'chat'|'revision'>('revision'),[attachments,setAttachments]=useState<File[]>([]);
 const [sending,setSending]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[offline,setOffline]=useState(false),[resuming,setResuming]=useState(false),[refresh,setRefresh]=useState(0);
 const messageId=useRef<string|null>(null),picker=useRef<HTMLInputElement>(null),transcript=useRef<HTMLDivElement>(null),requestRef=useRef<XMLHttpRequest|null>(null);
 useEffect(()=>{let active=true;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
  async function poll(){try{const response=await fetch(`/api/jobs/${id}/conversation`,{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error();const next=await response.json() as Snapshot;if(!active)return;setData(prior=>{const all=new Map(prior.messages.map(m=>[m.id,m]));for(const m of next.messages)if(!all.has(m.id)||all.get(m.id)!.updatedAt<=m.updatedAt)all.set(m.id,m);return {...next,messages:[...all.values()].sort((a,b)=>a.seq-b.seq).slice(-200)};});setOffline(false);}catch{if(active)setOffline(true);}finally{if(active)timer=setTimeout(poll,3000);}}
  void poll();return()=>{active=false;controller.abort();clearTimeout(timer);};
 },[id,refresh]);
 useEffect(()=>()=>requestRef.current?.abort(),[]);
 useEffect(()=>{const node=transcript.current;if(node&&node.scrollHeight-node.scrollTop-node.clientHeight<180)node.scrollTo({top:node.scrollHeight,behavior:'smooth'});},[data.messages]);
 const changed=()=>{messageId.current=null;setError('');};
 function addFiles(items:File[]){const next=[...attachments,...items];if(!validFiles(next)){setError(w[15]);return;}changed();setAttachments(next);}
 async function send(){
  if(sending||(!text.trim()&&!attachments.length))return;setSending(true);setProgress(0);setError('');
  const clientId=messageId.current??crypto.randomUUID();messageId.current=clientId;
  const form=new FormData();form.set('id',clientId);form.set('kind',kind);form.set('body',text);for(const file of attachments)form.append('files',file);
  try{
   const value=await new Promise<{message:Message}>((resolve,reject)=>{const xhr=new XMLHttpRequest();requestRef.current=xhr;xhr.open('POST',`/api/jobs/${id}/conversation`);xhr.timeout=120000;xhr.upload.onprogress=event=>{if(event.lengthComputable)setProgress(Math.round(event.loaded/event.total*100));};xhr.onload=()=>{try{const value=JSON.parse(xhr.responseText);if(xhr.status<200||xhr.status>=300)reject(Error(value.error||w[14]));else resolve(value);}catch{reject(Error(w[14]));}};xhr.onerror=()=>reject(Error(w[14]));xhr.ontimeout=()=>reject(Error(w[14]));xhr.onabort=()=>reject(Error(w[14]));xhr.send(form);});
   setData(current=>({...current,messages:[...current.messages.filter(m=>m.id!==value.message.id),value.message].sort((a,b)=>a.seq-b.seq)}));setText('');setAttachments([]);messageId.current=null;setRefresh(n=>n+1);requestAnimationFrame(()=>transcript.current?.scrollTo({top:transcript.current.scrollHeight,behavior:'smooth'}));
  }catch(e){setError(e instanceof Error?e.message:w[14]);}finally{setSending(false);requestRef.current=null;}
 }
 async function resume(){setResuming(true);setError('');try{const response=await fetch(`/api/jobs/${id}/resume`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedUpdatedAt:updatedAt})});if(!response.ok){const value=await response.json() as {error?:string};throw Error(value.error||w[22]);}onResume();setRefresh(n=>n+1);}catch(e){setError(e instanceof Error?e.message:w[22]);}finally{setResuming(false);}}
 const terminal=['complete','failed'].includes(status);
 return <section className="conversation" aria-label={w[0]}>
  <div className="conversation-heading"><div><p className="eyebrow">LIVE CONVERSATION</p><h2>{w[0]}</h2></div><span className={`conversation-connection ${offline?'offline':''}`} aria-label={offline?w[13]:'Connected'}>●</span></div><p className="fineprint">{w[1]}</p>
  {offline&&<p className="error" role="status">{w[13]}</p>}
  <div ref={transcript} className="conversation-transcript" role="log" aria-live="polite" aria-relevant="additions text">
   {!data.messages.length?<p className="conversation-empty">{w[12]}</p>:data.messages.map(m=><article className={`conversation-message ${m.role}`} key={m.id} data-message-id={m.id}><header><strong>{m.role==='user'?w[11]:'Codex'}</strong><time dateTime={new Date(m.createdAt).toISOString()}>{new Date(m.createdAt).toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit'})}</time></header><p>{m.body}</p>{m.attachments.length>0&&<ul>{m.attachments.map(file=><li key={file.id}><a href={`/api/jobs/${id}/conversation?message=${m.id}&file=${file.id}`}>{file.name} ↧</a><small>{(file.size/1024).toFixed(0)} KB</small></li>)}</ul>}{m.role==='user'&&<small className={`message-status ${m.status}`}>{m.kind==='revision'?w[2]:w[3]} · {m.status==='applied'?w[10]:m.status==='received'?w[9]:w[8]}</small>}</article>)}
  </div>{data.messages.length>=200&&<p className="fineprint">{w[25]}</p>}
  <form className="conversation-composer" onSubmit={event=>{event.preventDefault();void send();}} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(!sending)addFiles([...event.dataTransfer.files]);}}>
   <div className="conversation-modes">{(['revision','chat'] as const).map((value,index)=><button key={value} type="button" aria-pressed={kind===value} disabled={sending} onClick={()=>{changed();setKind(value);}}>{w[index+2]}</button>)}</div>
   <label className="sr-only" htmlFor={`message-${id}`}>{w[4]}</label><textarea id={`message-${id}`} value={text} onChange={event=>{changed();setText(event.target.value);}} maxLength={8000} disabled={sending} placeholder={w[4]} rows={4} onKeyDown={event=>{if(event.key==='Enter'&&(event.metaKey||event.ctrlKey)){event.preventDefault();void send();}}} onPaste={event=>{if(event.clipboardData.files.length){event.preventDefault();addFiles([...event.clipboardData.files]);}}}/>
   {attachments.length>0&&<ul className="conversation-uploads">{attachments.map((file,index)=><li key={`${file.name}-${index}`}><span>{file.name}</span><button type="button" disabled={sending} aria-label={`${w[21]} ${file.name}`} onClick={()=>{changed();setAttachments(all=>all.filter((_,n)=>n!==index));}}>×</button></li>)}</ul>}
   <input ref={picker} className="sr-only" type="file" multiple accept={extensions.map(e=>'.'+e).join(',')} onChange={event=>{addFiles([...event.target.files??[]]);event.target.value='';}} disabled={sending} aria-label={w[5]}/>
   <div className="conversation-send"><button type="button" onClick={()=>picker.current?.click()} disabled={sending}>＋ {w[5]}</button><button className="conversation-submit" disabled={sending||(!text.trim()&&!attachments.length)} type="submit">{sending?`${w[7]} ${progress}%`:`${w[6]} ↑`}</button></div>
   {sending&&<progress max={100} value={progress} aria-label={w[7]}/>}<p className="fineprint">{w[15]} {w[24]}</p>
  </form>{error&&<p className="error" role="alert">{error}</p>}
  {terminal&&data.recovery?.resumable&&<div className="conversation-recovery"><p>{w[17]}</p><button disabled={resuming} onClick={()=>void resume()}>{resuming?'…':w[16]} ↗</button></div>}
  {data.recovery&&<p className="fineprint">{w[18]} · {new Date(data.recovery.updatedAt).toLocaleTimeString(locale)}</p>}
  {data.versions.length>0&&<details className="conversation-versions"><summary>{w[19]} ({data.versions.length})</summary><ul>{data.versions.map(v=><li key={v.id}><time>{new Date(v.created_at).toLocaleString(locale)}</time>{!!v.pptx&&<a href={`/api/jobs/${id}/versions/${v.id}`}>PPTX ↓</a>}{!!v.bundle&&<a href={`/api/jobs/${id}/versions/${v.id}?kind=bundle`}>{w[20]} ↓</a>}</li>)}</ul></details>}
 </section>;
}
