import {memo,useCallback,useRef,useSyncExternalStore} from 'react';
import type {ReactNode} from 'react';
import type {SceneNode,Dict} from '../core/types';
import {Runtime} from '../core/runtime';
import {bindNode} from '../core/bindings';
import {logicalPoint} from '../core/coordinates';
import {equal} from '../core/state';
import {HtmlRenderer} from './HtmlRenderer';
import {CanvasRenderer} from './CanvasRenderer';
export function useSelected<T>(runtime:Runtime,select:(env:any)=>T){const cache=useRef<T>(undefined as T);const get=useCallback(()=>{const next=select(runtime.store.environment());if(!equal(cache.current,next))cache.current=next;return cache.current;},[runtime,select]);const subscribe=useCallback((fn:()=>void)=>runtime.store.subscribe(select,fn),[runtime,select]);return useSyncExternalStore(subscribe,get,get);}
export function layoutChildren(nodes:SceneNode[],p:Dict){const padding=Number(p.padding??0),gap=Number(p.gap??0),w=p.width??100,h=p.height??100;let pos=padding;const row=p.layout==='row',column=p.layout==='column';const total=nodes.reduce((s,c)=>s+Number(c.props?.[row?'width':'height']??(row?100:40)),0)+gap*(nodes.length-1);if(p.justify==='center')pos=Math.max(padding,((row?w:h)-total)/2);if(p.justify==='end')pos=Math.max(padding,(row?w:h)-padding-total);const actualGap=p.justify==='space-between'&&nodes.length>1?((row?w:h)-2*padding-(total-gap*(nodes.length-1)))/(nodes.length-1):gap;return nodes.map((child,i)=>{let off={x:0,y:0};if(row||column){const cross=Number(child.props?.[row?'height':'width']??(row?40:100)),size=row?h:w;const align=p.align==='center'?(size-cross)/2:p.align==='end'?size-padding-cross:padding;off=row?{x:pos,y:align}:{x:align,y:pos};pos+=Number(child.props?.[row?'width':'height']??(row?100:40))+actualGap;}if(p.layout==='grid'){const columns=p.columns??Math.ceil(Math.sqrt(nodes.length));off={x:padding+(i%columns)*((w-2*padding+gap)/columns),y:padding+Math.floor(i/columns)*((h-2*padding+gap)/(p.rows??Math.ceil(nodes.length/columns)))};}return{child,off};});}
export const NodeRenderer=memo(function NodeRenderer({node,runtime,locals={},offset={x:0,y:0},prefix=''}:{node:SceneNode;runtime:Runtime;locals?:Dict;offset?:{x:number;y:number};prefix?:string}){
 const selector=useCallback((env:any)=>{const environment={...env,locals};return {p:bindNode(node,environment,runtime.expressions),repeat:node.repeat?runtime.expressions.value(node.repeat.source,environment):null,visibility:env.state._visibility?.[node.id]};},[node,locals,runtime]);const {p,repeat,visibility}=useSelected(runtime,selector);const ref=useRef<SVGGElement>(null);const baseId=prefix+node.id;
 const event=(type:string,e:any)=>{if(type==='pointerDown')e.currentTarget.setPointerCapture?.(e.pointerId);const svg=ref.current?.ownerSVGElement;if(!svg)return;const pos=logicalPoint(e.clientX??0,e.clientY??0,svg.getBoundingClientRect(),runtime.scene.viewport);let local={x:pos.x,y:pos.y};const matrix=ref.current?.getScreenCTM();if(matrix){const q=new DOMPoint(e.clientX??0,e.clientY??0).matrixTransform(matrix.inverse());local={x:q.x,y:q.y};}const context={type,target:node.id,timestamp:performance.now(),...pos,localX:local.x,localY:local.y,key:e.key,shiftKey:e.shiftKey,ctrlKey:e.ctrlKey,altKey:e.altKey,metaKey:e.metaKey,deltaY:e.deltaY,value:e.target?.type==='checkbox'?e.target.checked:['range','number'].includes(e.target?.type)?Number(e.target.value):e.target?.value??p.value,locals};runtime.emit(context,{...p,id:node.id});if(prefix)runtime.emit({...context,target:prefix.slice(0,-1),child:node.id},p);};
 if(!p.visible||visibility===false)return null;if(node.repeat){if(!Array.isArray(repeat)||repeat.length>10000)throw new Error('Repeat requires at most 10000 rows');const keys=new Set<string>();return <>{repeat.map((item:any,index:number)=>{const local={...locals,[node.repeat!.item]:item,index};const key=String(runtime.expressions.value(node.repeat!.key,runtime.store.environment(local)));if(keys.has(key))throw new Error('Duplicate repetition key');keys.add(key);return <NodeRenderer key={key} runtime={runtime} node={{...node,repeat:undefined}} locals={local} offset={offset} prefix={prefix+key+'-'}/>;})}</>;}
 const w=p.width??100,h=p.height??40,x=(p.x??0)+offset.x,y=(p.y??0)+offset.y,interactive=(runtime.scene.interactions??[]).some(i=>i.target===node.id)||(runtime.scene.behaviors??[]).some(i=>i.target===node.id);const shape:any={fill:p.fill??runtime.scene.theme?.text??'#172033',stroke:p.stroke??'none',strokeWidth:p.strokeWidth??1};const origin=p.transformOrigin??{};let content:ReactNode;const points=Array.isArray(p.points)?p.points.map((v:number[])=>v.join(',')).join(' '):p.points;
 switch(node.type){case 'Group':content=layoutChildren([...(node.children??[])].sort((a,b)=>(a.props?.zIndex??0)-(b.props?.zIndex??0)),p).map(({child,off})=><NodeRenderer key={child.id} node={child} runtime={runtime} locals={locals} offset={off} prefix={prefix}/>);break;
 case 'component':content=runtime.components.render(node.component!,p,runtime.scene.theme??{}).map(child=><NodeRenderer key={child.id} node={child} runtime={runtime} locals={locals} prefix={baseId+'.'}/>);break;
 case 'Rect':case 'RoundedRect':content=<rect width={w} height={h} rx={p.radius??(node.type==='RoundedRect'?12:0)} {...shape}/>;break;
 case 'Circle':content=<circle r={p.radius??w/2} {...shape}/>;break;case 'Ellipse':content=<ellipse rx={w/2} ry={h/2} {...shape}/>;break;
 case 'Line':case 'Arrow':content=<><defs><marker id={'arrow-'+baseId} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill={p.stroke??'#172033'}/></marker></defs><line x1={0} y1={0} x2={(p.x2??x+w)-x} y2={(p.y2??y)-y} {...shape} markerEnd={node.type==='Arrow'?`url(#arrow-${baseId})`:undefined}/></>;break;
 case 'Polyline':content=<polyline points={points} {...shape}/>;break;case 'Polygon':content=<polygon points={points} {...shape}/>;break;case 'Path':content=<path d={p.d} {...shape} fillRule={p.fillRule??'nonzero'}/>;break;
 case 'Image':content=<image width={w} height={h} href={runtime.assets.resolve(p.src)} preserveAspectRatio={p.fit==='cover'?'xMidYMid slice':'xMidYMid meet'}/>;break;
 case 'Icon':{const paths:Dict={play:'M6 3L21 12L6 21Z',pause:'M6 4H10V20H6ZM14 4H18V20H14Z',reset:'M4 11A8 8 0 1 1 5 17M4 4V11H11',check:'M4 12L10 18L21 5',plus:'M12 3V21M3 12H21',minus:'M3 12H21',close:'M4 4L20 20M20 4L4 20',info:'M12 10V18M12 6V7'};if(!paths[p.name])throw new Error('Unknown icon');content=<svg width={w} height={h} viewBox="0 0 24 24"><path d={paths[p.name]} fill="none" stroke={p.fill??'#172033'} strokeWidth="2"/></svg>;break;}
 case 'Canvas':content=<CanvasRenderer p={p}/>;break;default:content=<HtmlRenderer type={node.type} p={{...p,id:baseId}} runtime={runtime} onEvent={event}/>;
 }
 const handlers:any={};for(const [name,type]of Object.entries({onClick:'click',onDoubleClick:'doubleClick',onPointerDown:'pointerDown',onPointerMove:'pointerMove',onPointerUp:'pointerUp',onPointerCancel:'pointerCancel',onPointerEnter:'hoverEnter',onPointerLeave:'hoverLeave',onWheel:'wheel',onFocus:'focus',onBlur:'blur'}))handlers[name]=(e:any)=>event(type,e);handlers.onKeyDown=(e:any)=>{event('keyboard',e);if(interactive&&['Enter',' '].includes(e.key)&&!['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName)){e.preventDefault();event('click',e);}};
 return <g ref={ref} data-node-id={baseId} data-node-type={node.type} transform={`translate(${x} ${y}) rotate(${p.rotation??0} ${origin.x??0} ${origin.y??0}) scale(${p.scale??1})`} opacity={p.opacity??1} role={interactive?'button':undefined} tabIndex={interactive?0:undefined} aria-label={p.ariaLabel??node.ariaLabel} style={{cursor:interactive?'pointer':undefined,touchAction:interactive?'none':undefined}} {...handlers}><defs>{p.clip&&<clipPath id={'clip-'+baseId}><rect {...p.clip}/></clipPath>}{p.mask&&<mask id={'mask-'+baseId}><rect width={w} height={h} fill="white"/><circle cx={p.mask.x} cy={p.mask.y} r={p.mask.radius} fill="black"/></mask>}</defs><g clipPath={p.clip?`url(#clip-${baseId})`:undefined} mask={p.mask?`url(#mask-${baseId})`:undefined}>{content}</g></g>;
});
