import {memo,useCallback,useMemo,useRef,useSyncExternalStore} from 'react';
import type {ReactNode,RefObject} from 'react';
import type {SceneNode,Dict} from '../core/types';
import {Runtime} from '../core/runtime';
import {bindNode} from '../core/bindings';
import {logicalPoint} from '../core/coordinates';
import {equal} from '../core/state';
import {HtmlRenderer} from './HtmlRenderer';
import {CanvasRenderer} from './CanvasRenderer';
import {FeatureNode,hasFeatureComponent} from '../feature-packs/index';
const EMPTY:Dict={},ZERO={x:0,y:0};
type Owner={node:SceneNode;p:Dict;ref:RefObject<SVGGElement|null>;baseId:string;locals:Dict};
const NO_PARENTS:Owner[]=[];
export function useSelected<T>(runtime:Runtime,select:(env:any)=>T){const cache=useRef<T>(undefined as T);const get=useCallback(()=>{const next=select(runtime.store.environment());if(!equal(cache.current,next))cache.current=next;return cache.current;},[runtime,select]);const subscribe=useCallback((fn:()=>void)=>runtime.store.subscribe(select,fn),[runtime,select]);return useSyncExternalStore(subscribe,get,get);}
export function layoutChildren(nodes:SceneNode[],p:Dict){const padding=Number(p.padding??0),gap=Number(p.gap??0),w=p.width??100,h=p.height??100;let pos=padding;const row=p.layout==='row',column=p.layout==='column';const total=nodes.reduce((s,c)=>s+Number(c.props?.[row?'width':'height']??(row?100:40)),0)+gap*Math.max(0,nodes.length-1);if(p.justify==='center')pos=Math.max(padding,((row?w:h)-total)/2);if(p.justify==='end')pos=Math.max(padding,(row?w:h)-padding-total);const actualGap=p.justify==='space-between'&&nodes.length>1?Math.max(0,((row?w:h)-2*padding-(total-gap*(nodes.length-1)))/(nodes.length-1)):gap;return nodes.map((child,i)=>{let off={x:0,y:0};if(row||column){const cross=Number(child.props?.[row?'height':'width']??(row?40:100)),size=row?h:w;const align=p.align==='center'?(size-cross)/2:p.align==='end'?size-padding-cross:padding;off=row?{x:pos,y:align}:{x:align,y:pos};pos+=Number(child.props?.[row?'width':'height']??(row?100:40))+actualGap;}if(p.layout==='grid'){const columns=Math.max(1,p.columns??Math.ceil(Math.sqrt(nodes.length))),rows=Math.max(1,p.rows??Math.ceil(nodes.length/columns));off={x:padding+(i%columns)*((w-2*padding+gap)/columns),y:padding+Math.floor(i/columns)*((h-2*padding+gap)/rows)};}return{child,off};});}
function enforceRenderBudget(runtime:Runtime,nodes:SceneNode[],env:any){let count=0;const visit=(list:SceneNode[],locals:Dict,depth:number)=>{if(depth>32)throw new Error('Rendered node nesting exceeded');for(const node of list){const expand=(local:Dict)=>{const bound=bindNode(node,{...env,locals:local},runtime.expressions);if(!bound.visible||env.state._visibility?.[node.id]===false)return;if(++count>10000)throw new Error('Rendered node count exceeded');if(node.type==='Group')visit(node.children??[],local,depth+1);else if(node.type==='component'&&runtime.components.has(node.component!))visit(runtime.components.render(node.component!,bound,runtime.scene.theme??{}),{...local,props:bound},depth+1);};if(node.repeat){const values=runtime.expressions.value(node.repeat.source,{...env,locals});if(!Array.isArray(values)||values.length>10000)throw new Error('Repeat requires at most 10000 rows');for(let index=0;index<values.length;index++)expand({...locals,[node.repeat.item]:values[index],index});}else expand(locals);}};visit(nodes,{},0);}
/** Resolve layout from current bound dimensions and expanded repetition. Only a
 * changed arrangement updates this component; leaf values retain subscriptions. */
export const NodeList=memo(function NodeList({nodes,runtime,locals=EMPTY,p=EMPTY,prefix='',parents=NO_PARENTS}:{nodes:SceneNode[];runtime:Runtime;locals?:Dict;p?:Dict;prefix?:string;parents?:Owner[]}){
 const selector=useCallback((env:any)=>{if(!parents.length)enforceRenderBudget(runtime,nodes,env);const expanded:{node:SceneNode;locals:Dict;prefix:string;p:Dict}[]=[];for(const node of nodes){const append=(current:SceneNode,local:Dict,pre:string)=>{const bound=bindNode(current,{...env,locals:local},runtime.expressions);if(!bound.visible||env.state._visibility?.[current.id]===false)return;expanded.push({node:current,locals:local,prefix:pre,p:{width:bound.width,height:bound.height,zIndex:bound.zIndex??0}});};if(node.repeat){const values=runtime.expressions.value(node.repeat.source,{...env,locals});if(!Array.isArray(values)||values.length>10000)throw new Error('Repeat requires at most 10000 rows');const keys=new Set<string>();values.forEach((item:any,index:number)=>{const local={...locals,[node.repeat!.item]:item,index},key=String(runtime.expressions.value(node.repeat!.key,{...env,locals:local}));if(keys.has(key))throw new Error('Duplicate repetition key');keys.add(key);append({...node,repeat:undefined},local,prefix+encodeURIComponent(key)+'-');});}else append(node,locals,prefix);}expanded.sort((a,b)=>a.p.zIndex-b.p.zIndex);const arranged=layoutChildren(expanded.map(x=>({...x.node,props:x.p})),p);return expanded.map((item,i)=>({node:item.node,locals:item.locals,prefix:item.prefix,offset:arranged[i].off}));},[nodes,locals,prefix,p,runtime,parents]);
 const arranged=useSelected(runtime,selector);return <>{arranged.map(item=><NodeRenderer key={item.prefix+item.node.id} {...item} runtime={runtime} parents={parents}/>)}</>;
});
export const NodeRenderer=memo(function NodeRenderer({node,runtime,locals=EMPTY,offset=ZERO,prefix='',parents=NO_PARENTS}:{node:SceneNode;runtime:Runtime;locals?:Dict;offset?:{x:number;y:number};prefix?:string;parents?:Owner[]}){
 const selector=useCallback((env:any)=>{if(node.repeat)return {p:{visible:true},visibility:true};return {p:bindNode(node,{...env,locals},runtime.expressions),visibility:env.state._visibility?.[node.id]};},[node,locals,runtime]);
 const {p,visibility}=useSelected(runtime,selector),ref=useRef<SVGGElement>(null),baseId=prefix+node.id;
 const owner=useRef<Owner>({node,p,ref,baseId,locals});Object.assign(owner.current,{node,p,ref,baseId,locals});const childParents=useMemo(()=>[owner.current,...parents],[parents]);
 const event=(type:string,e:any,override?:any)=>{
  e.stopPropagation?.();const svg=ref.current?.ownerSVGElement;if(!svg)return;
  const pointerMechanics=childParents.some(o=>(runtime.scene.behaviors??[]).some(b=>b.target===o.node.id&&['drag','resize','pan','panZoom','brush','scrub'].includes(b.type)));
  if(type==='pointerDown'&&pointerMechanics&&e.pointerId!==undefined)ref.current?.setPointerCapture?.(e.pointerId);
  if(type==='wheel'&&childParents.some(o=>(runtime.scene.behaviors??[]).some(b=>b.target===o.node.id&&['zoom','panZoom'].includes(b.type))))e.preventDefault?.();
  const pos=logicalPoint(e.clientX??0,e.clientY??0,svg.getBoundingClientRect(),runtime.scene.viewport);
  const target=e.target??{},formValue=target.type==='checkbox'?target.checked:['range','number'].includes(target.type)?Number(target.value):['INPUT','SELECT','TEXTAREA'].includes(target.tagName)?target.value:p.eventValue??p.value;
  const common={type,timestamp:performance.now(),...pos,pointerId:e.pointerId,key:e.key,shiftKey:e.shiftKey,ctrlKey:e.ctrlKey,altKey:e.altKey,metaKey:e.metaKey,deltaY:e.deltaY,value:override===undefined?formValue:override,sourceTarget:baseId,child:node.id};
  for(const o of childParents){let local={x:pos.x,y:pos.y},parent=local;const matrix=o.ref.current?.getScreenCTM(),parentMatrix=(o.ref.current?.parentElement as any)?.getScreenCTM?.();if(matrix){const point=new DOMPoint(e.clientX??0,e.clientY??0).matrixTransform(matrix.inverse());local={x:point.x,y:point.y};}if(parentMatrix){const point=new DOMPoint(e.clientX??0,e.clientY??0).matrixTransform(parentMatrix.inverse());parent={x:point.x,y:point.y};}runtime.emit({...common,target:o.node.id,instanceId:o.baseId,localX:local.x,localY:local.y,parentX:parent.x,parentY:parent.y,locals:o.locals},{...o.p,id:o.node.id});}
  runtime.emit({...common,target:'scene',locals});
 };
 if(node.repeat)return <NodeList nodes={[node]} runtime={runtime} locals={locals} prefix={prefix} parents={parents}/>;
 if(!p.visible||visibility===false)return null;
 const w=p.width??100,h=p.height??40,x=(p.x??0)+offset.x,y=(p.y??0)+offset.y;
 const interactive=(runtime.scene.interactions??[]).some(i=>i.target===node.id)||(runtime.scene.behaviors??[]).some(i=>i.target===node.id),nativeControl=['Button','Input','Textarea','Slider','Toggle','Select','FileInput','Video','Audio'].includes(node.type);
 const shape:any={fill:p.fill??runtime.scene.theme?.text??'#172033',stroke:p.stroke??'none',strokeWidth:p.strokeWidth??1};const origin=p.transformOrigin??{};let content:ReactNode;const points=Array.isArray(p.points)?p.points.map((v:number[])=>v.join(',')).join(' '):p.points;
 switch(node.type){
 case 'Group':content=<NodeList nodes={node.children??[]} p={p} runtime={runtime} locals={locals} prefix={prefix} parents={childParents}/>;break;
 case 'component':content=hasFeatureComponent(runtime,node.component!)?<FeatureNode name={node.component!} p={p} runtime={runtime} nodeId={node.id}/>:<NodeList nodes={runtime.components.render(node.component!,p,runtime.scene.theme??{})} runtime={runtime} locals={{...locals,props:p}} prefix={baseId+'.'} parents={childParents}/>;break;
 case 'Rect':case 'RoundedRect':content=<rect width={w} height={h} rx={p.radius??(node.type==='RoundedRect'?12:0)} {...shape}/>;break;
 case 'Circle':content=<circle r={p.radius??w/2} {...shape}/>;break;case 'Ellipse':content=<ellipse rx={w/2} ry={h/2} {...shape}/>;break;
 case 'Line':case 'Arrow':content=<><defs><marker id={'arrow-'+baseId} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill={p.stroke??'#172033'}/></marker></defs><line x1={0} y1={0} x2={(p.x2??(p.x??0)+w)-(p.x??0)} y2={(p.y2??p.y??0)-(p.y??0)} {...shape} markerEnd={node.type==='Arrow'?`url(#arrow-${baseId})`:undefined}/></>;break;
 case 'Polyline':content=<polyline points={points} {...shape}/>;break;case 'Polygon':content=<polygon points={points} {...shape}/>;break;case 'Path':content=<path d={p.d} {...shape} fillRule={p.fillRule??'nonzero'}/>;break;
 case 'Image':content=<image width={w} height={h} href={runtime.assets.resolve(p.src)} preserveAspectRatio={p.fit==='cover'?'xMidYMid slice':'xMidYMid meet'}/>;break;
 case 'Icon':{const paths:Dict={play:'M6 3L21 12L6 21Z',pause:'M6 4H10V20H6ZM14 4H18V20H14Z',reset:'M4 11A8 8 0 1 1 5 17M4 4V11H11',check:'M4 12L10 18L21 5',plus:'M12 3V21M3 12H21',minus:'M3 12H21',close:'M4 4L20 20M20 4L4 20',info:'M12 10V18M12 6V7'};if(!paths[p.name])throw new Error('Unknown icon');content=<svg width={w} height={h} viewBox="0 0 24 24"><path d={paths[p.name]} fill="none" stroke={p.fill??'#172033'} strokeWidth="2"/></svg>;break;}
 case 'Canvas':content=<CanvasRenderer p={p}/>;break;
 default:content=<HtmlRenderer type={node.type} p={{...p,id:baseId}} runtime={runtime} onEvent={event}/>;
 }
 const handlers:any={};for(const [name,type]of Object.entries({onClick:'click',onDoubleClick:'doubleClick',onPointerDown:'pointerDown',onPointerMove:'pointerMove',onPointerUp:'pointerUp',onPointerCancel:'pointerCancel',onWheel:'wheel',onFocus:'focus',onBlur:'blur'}))handlers[name]=(e:any)=>event(type,e);
 handlers.onPointerOver=(e:any)=>{if(!(e.relatedTarget instanceof Node)||!ref.current?.contains(e.relatedTarget))event('hoverEnter',e);};handlers.onPointerOut=(e:any)=>{if(!(e.relatedTarget instanceof Node)||!ref.current?.contains(e.relatedTarget))event('hoverLeave',e);};
 handlers.onKeyDown=(e:any)=>{event('keyboard',e);if(interactive&&['Enter',' '].includes(e.key)&&!['INPUT','TEXTAREA','SELECT','BUTTON','VIDEO','AUDIO'].includes(e.target.tagName)){e.preventDefault();event('click',e);}};
 return <g ref={ref} data-node-id={baseId} data-node-type={node.type} transform={`translate(${x} ${y}) rotate(${p.rotation??0} ${origin.x??0} ${origin.y??0}) scale(${p.scale??1})`} opacity={p.opacity??1} role={interactive&&!nativeControl?'button':undefined} tabIndex={interactive&&!nativeControl?0:undefined} aria-label={nativeControl?undefined:p.ariaLabel??node.ariaLabel} aria-pressed={interactive&&typeof p.selected==='boolean'?p.selected:undefined} style={{cursor:interactive?'pointer':undefined,touchAction:interactive?'none':undefined}} {...handlers}><defs>{p.clip&&<clipPath id={'clip-'+baseId}><rect {...p.clip}/></clipPath>}{p.mask&&<mask id={'mask-'+baseId}><rect width={w} height={h} fill="white"/><circle cx={p.mask.x} cy={p.mask.y} r={p.mask.radius} fill="black"/></mask>}</defs><g clipPath={p.clip?`url(#clip-${baseId})`:undefined} mask={p.mask?`url(#mask-${baseId})`:undefined}>{content}</g></g>;
});
