import {Component,useEffect,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import type {Runtime} from '../core/runtime';
import {NodeList} from './NodeRenderer';
import {diagnosticOf} from '../core/diagnostics';
export class RuntimeErrorBoundary extends Component<{children:ReactNode;debug?:boolean;sceneId?:string},{error:Error|null}>{state={error:null as Error|null};static getDerivedStateFromError(error:Error){return{error};}render(){return this.state.error?<div role="alert" className="error"><p>Interactive content unavailable.</p><p>Static slide content remains available.</p>{this.props.debug&&<pre data-diagnostic>{JSON.stringify(diagnosticOf(this.state.error,{sceneId:this.props.sceneId}),null,2)}</pre>}</div>:this.props.children;}}
export function SceneRoot({runtime}:{runtime:Runtime}){const ref=useRef<HTMLDivElement>(null);const [error,setError]=useState<Error|null>(null),[size,setSize]=useState({width:0,height:0});useEffect(()=>{runtime.onError=setError;const observer=new ResizeObserver(([entry])=>setSize({width:entry.contentRect.width,height:entry.contentRect.height}));if(ref.current)observer.observe(ref.current);return()=>{observer.disconnect();runtime.onError=null;};},[runtime]);if(error)throw error;const s=runtime.scene;return <div ref={ref} className="scene" data-ready={runtime.ready} style={{background:s.runtimeOptions?.transparent?'transparent':s.theme?.background??'#fff'}}><svg role="group" aria-label={s.id} viewBox={`0 0 ${s.viewport.width} ${s.viewport.height}`} width="100%" height="100%" preserveAspectRatio="xMidYMid meet"><NodeList nodes={s.nodes} runtime={runtime}/></svg>{s.runtimeOptions?.debug&&<Diagnostics runtime={runtime} size={size}/>}</div>;}
function Diagnostics({runtime,size}:any){
 const [frames,setFrames]=useState({fps:0,p95:0}),[sizes,setSizes]=useState<any>(null);
 useEffect(()=>{let frame=0,start=performance.now(),last=start;let times:number[]=[];const tick=(time:number)=>{if(time>=last)times.push(time-last);last=Math.max(last,time);if(time-start>=1000){const sorted=[...times].sort((a,b)=>a-b);setFrames({fps:Math.round(times.length*1000/(time-start)),p95:sorted[Math.floor((sorted.length-1)*.95)]??0});start=time;times=[];}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[]);
 useEffect(()=>{const abort=new AbortController();fetch(new URL('./bundle-sizes.json',location.href),{signal:abort.signal,credentials:'omit'}).then(r=>{if(!r.ok)throw new Error('Size manifest unavailable');return r.json();}).then(setSizes).catch(()=>{});return()=>abort.abort();},[]);
 const kib=(bytes:number)=>`${(bytes/1024).toFixed(1)} KiB`,packs=Object.entries(sizes?.featurePacks??{}).map(([name,value]:any)=>`${name}: JS ${kib(value.javascriptGzipBytes)}, local assets ${(value.localAssetBytes/1048576).toFixed(1)} MiB`).join(' · ');
 return <output className="diagnostics" style={{maxWidth:'calc(100% - 18px)',maxHeight:'30%',overflow:'auto',pointerEvents:'none'}} data-rendered-nodes={runtime.metrics.nodes} data-bindings={runtime.metrics.bindings}>
  <div>{runtime.metrics.nodes} rendered nodes · {runtime.metrics.bindings} bindings · {Object.values(runtime.timeline.states).filter((s:any)=>s.playing).length} active timelines · {frames.fps} fps · frame p95 {frames.p95.toFixed(1)} ms · {Math.round(size.width)}×{Math.round(size.height)}</div>
  {runtime.metrics.canvasAdvisory&&<div>At least {runtime.metrics.canvasThreshold} scene nodes: consider explicit Canvas for dense marks after checking equivalent visuals and accessibility. Rendering is unchanged.</div>}
  <div>{sizes?`Core JS gzip ${kib(sizes.coreGzipBytes)} · ${packs}`:'Bundle sizes unavailable in this preview; production build writes bundle-sizes.json.'}</div>
 </output>;
}
