import type {Dict,SceneNode} from '../core/types';
export type ComponentFactory=(props:Dict,theme:Dict)=>SceneNode[];
export class ComponentRegistry {
 private factories=new Map<string,ComponentFactory>();
 register(name:string,factory:ComponentFactory){if(this.factories.has(name))throw new Error(`Duplicate component ${name}`);this.factories.set(name,factory);}
 render(name:string,props:Dict,theme:Dict){const fn=this.factories.get(name);if(!fn)throw new Error(`Unknown component ${name}`);let nodes:SceneNode[];try{nodes=fn(props,theme);}catch(error){throw new Error(`Component ${name}: ${error instanceof Error?error.message:String(error)}`,{cause:error});}if(nodes.length>10000)throw new Error('Component node count exceeded');return nodes;}
 has(name:string){return this.factories.has(name);}
}
const n=(id:string,type:string,props:Dict):SceneNode=>({id,type,props});
const defaultPalette=['#2563eb','#f97316','#0d9488','#8b5cf6','#e11d48'];
const colors=(p:Dict,t:Dict)=>p.colors??t.palette??[t.accent??defaultPalette[0],...defaultPalette.slice(1)];
const number=(v:any)=>{const result=Number(v);if(!Number.isFinite(result))throw new Error('Component data requires finite numbers');return result;};
const sum=(a:number[])=>a.reduce((a,b)=>a+b,0);
export function registerComponents(r:ComponentRegistry){
 const bars=(p:Dict,theme:Dict,mode='bar')=>{
  const data=p.data??[],w=p.width??800,h=p.height??400,palette=colors(p,theme),rows=data.map((row:any)=>({row,values:(row.values??[row.value??row]).map(number)}));
  const upper=p.max??Math.max(0,...rows.map(({values}:any)=>mode==='stacked'?sum(values.filter((v:number)=>v>0)):Math.max(...values))),lower=p.min??Math.min(0,...rows.map(({values}:any)=>mode==='stacked'?sum(values.filter((v:number)=>v<0)):Math.min(...values)));
  const range=upper-lower||1,plot=Math.max(1,h-42),yFor=(v:number)=>(upper-v)/range*plot,bw=w/Math.max(1,data.length);
  return rows.flatMap(({row,values}:any,i:number)=>{let positive=0,negative=0;const out=values.map((v:number,j:number)=>{const start=mode==='stacked'?(v>=0?positive:negative):0,end=start+v;if(v>=0)positive=end;else negative=end;const eventValue={index:i,series:j,label:row.label??String(i),value:v};return n(`bar-${i}-${j}`,'Rect',{x:i*bw+(mode==='grouped'?j*bw/values.length:0)+4,y:Math.min(yFor(start),yFor(end)),width:Math.max(1,(mode==='grouped'?bw/values.length:bw)-8),height:Math.abs(v)/range*plot,fill:row.color??palette[j%palette.length],stroke:p.selected===i?(theme.text??'#172033'):'none',strokeWidth:p.selected===i?3:0,ariaLabel:`${row.label??i}, series ${j+1}: ${v}`,selected:p.selected===i,eventValue});});out.push(n(`label-${i}`,'Text',{x:i*bw+4,y:h-30,width:Math.max(1,bw-8),height:30,text:String(row.label??i),fontSize:p.labelSize??16,fill:theme.text??'#172033',eventValue:{index:i,label:row.label??String(i)}}));return out;});
 };
 r.register('barChart',(p,t)=>bars(p,t));r.register('groupedBarChart',(p,t)=>bars(p,t,'grouped'));r.register('stackedBarChart',(p,t)=>bars(p,t,'stacked'));
 for(const kind of ['lineChart','areaChart','scatterChart'])r.register(kind,(p,t)=>{
  const data=p.data??[],w=p.width??800,h=p.height??400,points=data.map((v:any,i:number)=>[number(v.x??i),number(v.y??v.value??v)]),minX=p.minX??Math.min(0,...points.map((v:number[])=>v[0])),maxX=p.maxX??Math.max(1,...points.map((v:number[])=>v[0])),minY=p.minY??Math.min(0,...points.map((v:number[])=>v[1])),maxY=p.maxY??Math.max(1,...points.map((v:number[])=>v[1]));
  const yFor=(v:number)=>h-30-(v-minY)/(maxY-minY||1)*(h-50),pts=points.map(([x,y]:number[])=>[(x-minX)/(maxX-minX||1)*w,yFor(y)]),color=p.color??colors(p,t)[0];
  if(kind==='scatterChart')return pts.map(([x,y]:number[],i:number)=>n('point-'+i,'Circle',{x,y,radius:p.radius??7,fill:color,stroke:p.selected===i?(t.text??'#172033'):'none',strokeWidth:3,ariaLabel:`${points[i][0]}, ${points[i][1]}`,eventValue:{index:i,x:points[i][0],y:points[i][1]}}));
  return[n('series',kind==='areaChart'?'Polygon':'Polyline',{points:kind==='areaChart'?[[0,yFor(0)],...pts,[w,yFor(0)]]:pts,stroke:color,strokeWidth:p.strokeWidth??4,fill:kind==='areaChart'?(p.fill??color):'none',opacity:kind==='areaChart'?.65:1})];
 });
 for(const kind of ['heatmap','matrix'])r.register(kind,(p,t)=>{const data=p.data??[],columns=data[0]?.length||1;if(data.some((row:any)=>!Array.isArray(row)||row.length!==columns))throw new Error('Matrix rows must have equal length');const cw=(p.width??500)/columns,ch=(p.height??400)/(data.length||1),max=p.max??Math.max(1,...data.flat().map((v:any)=>Math.abs(number(v))));return data.flatMap((row:any[],y:number)=>row.flatMap((raw:any,x:number)=>{const v=number(raw),selected=p.selected?.[0]===y&&p.selected?.[1]===x,eventValue={row:y,column:x,value:v};return[n(`cell-${y}-${x}`,'Rect',{x:x*cw,y:y*ch,width:Math.max(1,cw-2),height:Math.max(1,ch-2),fill:selected?'#ffedd5':`rgb(${Math.round(240-Math.min(1,Math.abs(v)/max)*180)},${Math.round(246-Math.min(1,Math.abs(v)/max)*100)},250)`,stroke:selected?(t.text??'#172033'):'none',strokeWidth:selected?3:0,ariaLabel:`row ${y+1}, column ${x+1}: ${v}`,eventValue}),n(`value-${y}-${x}`,'Text',{x:x*cw,y:y*ch,width:cw,height:ch,text:String(v),fontSize:Math.min(28,ch*.4),textAlign:'center',fill:t.text??'#172033',eventValue})];}));});
 r.register('table',(p,t)=>{const data=p.data??[],columns=p.columns??(data[0]&&!Array.isArray(data[0])?Object.keys(data[0]):[]),labels=columns.map((c:any)=>typeof c==='string'?c:c.label??c.key),rows=[labels,...data.map((row:any)=>Array.isArray(row)?row:columns.map((c:any)=>row[typeof c==='string'?c:c.key]))],cw=(p.width??800)/Math.max(1,columns.length),ch=p.rowHeight??44;return rows.flatMap((row:any[],y:number)=>row.flatMap((v,x)=>{const eventValue={row:y-1,column:x,key:columns[x]?.key??columns[x],value:v};return[n(`bg-${y}-${x}`,'Rect',{x:x*cw,y:y*ch,width:cw,height:ch,fill:y===0?(t.surface??'#dbeafe'):y%2?'#f8fafc':'white',stroke:p.selected===y-1?(t.accent??defaultPalette[0]):'#e2e8f0',strokeWidth:p.selected===y-1?3:1,eventValue}),n(`text-${y}-${x}`,'Text',{x:x*cw+8,y:y*ch+4,width:Math.max(1,cw-16),height:Math.max(1,ch-8),text:String(v??''),fontSize:p.fontSize??18,fill:t.text??'#172033',bold:y===0,eventValue})];}));});
 r.register('KPI',(p,t)=>[n('value','Text',{width:p.width??400,height:p.valueHeight??90,text:String(p.value??0),fontSize:p.fontSize??64,fill:p.color??t.accent??defaultPalette[0]}),n('label','Text',{y:p.valueHeight??95,width:p.width??400,height:40,text:p.label??'',fontSize:24,fill:t.text??'#172033'})]);
 r.register('progress',(p,t)=>[n('track','RoundedRect',{width:p.width??400,height:p.height??24,radius:12,fill:t.surface??'#e2e8f0'}),n('fill','RoundedRect',{width:(p.width??400)*Math.max(0,Math.min(1,p.value??0)),height:p.height??24,radius:12,fill:p.color??t.accent??defaultPalette[0],ariaLabel:`${Math.round((p.value??0)*100)} percent`})]);
 r.register('network',(p,t)=>{const nodes=p.nodes??[],byId=Object.fromEntries(nodes.map((v:any)=>[v.id,v]));return [...(p.edges??[]).map((e:any,i:number)=>{if(!byId[e.from]||!byId[e.to])throw new Error('Network edge references missing node');return n('edge-'+i,'Arrow',{x:byId[e.from].x,y:byId[e.from].y,x2:byId[e.to].x,y2:byId[e.to].y,stroke:e.color??t.muted??'#94a3b8',strokeWidth:e.width??2,eventValue:{index:i,from:e.from,to:e.to}});}),...nodes.flatMap((v:any)=>[n('node-'+v.id,'Circle',{x:v.x,y:v.y,radius:v.radius??24,fill:v.color??t.accent??defaultPalette[0],stroke:p.selected===v.id?(t.text??'#172033'):'none',strokeWidth:3,eventValue:{id:v.id}}),n('label-'+v.id,'Text',{x:v.x-70,y:v.y+28,width:140,height:30,text:v.label??v.id,fontSize:18,textAlign:'center',fill:t.text??'#172033',eventValue:{id:v.id}})])];});
 r.register('timeline',(p,t)=>(p.data??[]).flatMap((v:any,i:number)=>[n('event-'+i,'Circle',{x:12+i*Math.max(0,(p.width??800)-24)/Math.max(1,p.data.length-1),y:40,radius:12,fill:i<=(p.active??0)?(t.accent??defaultPalette[0]):'#94a3b8',stroke:i===(p.active??0)?(t.text??'#172033'):'none',strokeWidth:3,eventValue:i}),n('label-'+i,'Text',{x:i*Math.max(0,(p.width??800)-140)/Math.max(1,p.data.length-1),y:65,width:140,height:80,text:v.label??String(v),fontSize:18,fill:t.text??'#172033',eventValue:i})]));
 r.register('imageComparison',(p)=>{const w=p.width??600,h=p.height??400,x=w*Math.max(0,Math.min(1,p.position??.5));return[n('before','Image',{width:w,height:h,src:p.before}),n('after','Image',{width:w,height:h,src:p.after,clip:{x:0,y:0,width:x,height:h}}),n('divider','Line',{x,y:0,x2:x,y2:h,stroke:'#fff',strokeWidth:4})];});
 r.register('hotspotImage',(p,t)=>[n('image','Image',{width:p.width??600,height:p.height??400,src:p.src}),...(p.hotspots??[]).map((h:any,i:number)=>n('hotspot-'+i,'Button',{x:h.x,y:h.y,width:44,height:44,text:h.label??String(i+1),fill:t.accent??defaultPalette[0],ariaLabel:h.description??h.label??`Hotspot ${i+1}`,eventValue:{index:i,id:h.id??i}}))]);
 for(const kind of ['tabs','stepper'])r.register(kind,(p,t)=>{const items=p.items??[],w=(p.width??800)/Math.max(1,items.length);return items.map((v:any,i:number)=>n('item-'+i,'Button',{x:i*w,width:Math.max(1,w-8),height:p.height??48,text:typeof v==='string'?v:v.label,fill:i===(p.active??0)?(t.accent??defaultPalette[0]):'#475569',selected:i===(p.active??0),value:i}));});
 r.register('carousel',(p)=>{const item=p.items?.[p.active??0];return item?[n('slide','Image',{width:p.width??600,height:p.height??400,src:item.src??item,ariaLabel:item.label??`Slide ${(p.active??0)+1}`,eventValue:p.active??0})]:[n('empty','Text',{text:'No images',width:p.width??600,height:50})];});
 for(const kind of ['tooltip','popover'])r.register(kind,(p,t)=>p.open?[n('background','RoundedRect',{width:p.width??300,height:p.height??100,fill:t.text??'#172033',radius:8}),n('content','Text',{x:12,y:12,width:(p.width??300)-24,height:(p.height??100)-24,text:p.text,fontSize:18,fill:t.background??'white'})]:[]);
 r.register('geoJSON',(p,t)=>geo(p,t));
}
export function geo(p:Dict,theme:Dict={}):SceneNode[]{
 const width=p.width??800,height=p.height??500,scale=p.zoom??1,project=(v:number[])=>{if(!Array.isArray(v)||v.length<2)throw new Error('Invalid GeoJSON position');const lon=number(v[0]),lat=Math.max(-85,Math.min(85,number(v[1])));return [(lon+180)/360*width*scale+(p.panX??0),(p.projection==='mercator'?(1-Math.log(Math.tan(Math.PI/4+lat*Math.PI/360))/Math.PI)/2:(90-lat)/180)*height*scale+(p.panY??0)];};
 const layers=p.layers??[{data:p.data,id:'default'}];let globalIndex=0;
 return layers.flatMap((layer:any,layerIndex:number)=>{if(layer.visible===false)return[];const features=layer.data?.type==='Feature'?[layer.data]:layer.data?.features??[];return features.flatMap((f:any)=>{const i=globalIndex++,g=f.geometry;if(!g)return[];const selected=p.selected===(f.id??i),value={index:i,id:f.id??i,layer:layer.id??layerIndex,properties:f.properties??{}},props={fill:selected?(p.selectedFill??'#ffedd5'):f.properties?.fill??layer.fill??p.fill??theme.accent??'#93c5fd',stroke:layer.stroke??theme.text??'#334155',strokeWidth:selected?3:1,ariaLabel:f.properties?.name??String(f.id??i),eventValue:value};if(g.type==='Point'){const [x,y]=project(g.coordinates);return[n('geo-'+i,'Circle',{...props,x,y,radius:p.pointRadius??6})];}if(g.type==='LineString')return[n('geo-'+i,'Polyline',{...props,fill:'none',points:g.coordinates.map(project)})];if(['Polygon','MultiPolygon'].includes(g.type)){const polygons=g.type==='Polygon'?[g.coordinates]:g.coordinates;return polygons.map((rings:any[],j:number)=>n(`geo-${i}-${j}`,'Path',{...props,fillRule:'evenodd',d:rings.map(ring=>'M'+ring.map(project).map(v=>v.join(',')).join('L')+'Z').join(' ')}));}throw new Error(`Unsupported GeoJSON ${g.type}`);});});
}
