import type {Dict,SceneNode} from '../core/types';
export type ComponentFactory=(props:Dict,theme:Dict)=>SceneNode[];
export class ComponentRegistry {private factories=new Map<string,ComponentFactory>();register(name:string,factory:ComponentFactory){if(this.factories.has(name))throw new Error(`Duplicate component ${name}`);this.factories.set(name,factory);}render(name:string,props:Dict,theme:Dict){const fn=this.factories.get(name);if(!fn)throw new Error(`Unknown component ${name}`);return fn(props,theme);}has(name:string){return this.factories.has(name);}}
const n=(id:string,type:string,props:Dict):SceneNode=>({id,type,props});
const palette=['#2563eb','#f97316','#0d9488','#8b5cf6','#e11d48'];
export function registerComponents(r:ComponentRegistry){
 const bars=(p:Dict,theme:Dict,mode='bar')=>{const data=p.data??[],w=p.width??800,h=p.height??400,maximum=p.max??Math.max(1,...data.map((v:any)=>mode==='stacked'?sum(v.values??[v.value]):Math.max(v.value??0,...v.values??[]))),bw=w/Math.max(1,data.length);return data.flatMap((row:any,i:number)=>{const values=row.values??[row.value??row];let offset=0;const out=values.map((v:number,j:number)=>{const height=v/maximum*(h-42),x=i*bw+(mode==='grouped'?j*bw/values.length:0)+4,width=(mode==='grouped'?bw/values.length:bw)-8,y=h-42-height-(mode==='stacked'?offset:0);offset+=height;return n(`bar-${i}-${j}`,'Rect',{x,y,width,height,fill:row.color??palette[j%palette.length],ariaLabel:`${row.label??i}: ${v}`,selected:p.selected===i});});out.push(n(`label-${i}`,'Text',{x:i*bw+4,y:h-30,width:bw-8,height:30,text:String(row.label??i),fontSize:16,fill:theme.text??'#172033'}));return out;});};
 const sum=(a:number[])=>a.reduce((a,b)=>a+b,0);
 r.register('barChart',(p,t)=>bars(p,t));r.register('groupedBarChart',(p,t)=>bars(p,t,'grouped'));r.register('stackedBarChart',(p,t)=>bars(p,t,'stacked'));
 for(const kind of ['lineChart','areaChart','scatterChart'])r.register(kind,(p,t)=>{const data=p.data??[],w=p.width??800,h=p.height??400,maxX=p.maxX??Math.max(1,...data.map((v:any,i:number)=>v.x??i)),maxY=p.maxY??Math.max(1,...data.map((v:any)=>v.y??v.value??v));const pts=data.map((v:any,i:number)=>[(v.x??i)/maxX*w,h-30-(v.y??v.value??v)/maxY*(h-50)]);if(kind==='scatterChart')return pts.map(([x,y]:number[],i:number)=>n('point-'+i,'Circle',{x,y,radius:7,fill:p.color??palette[0],ariaLabel:`${data[i].x}, ${data[i].y}`}));return[n('series',kind==='areaChart'?'Polygon':'Polyline',{points:kind==='areaChart'?[[0,h-30],...pts,[w,h-30]]:pts,stroke:p.color??palette[0],strokeWidth:4,fill:kind==='areaChart'?(p.color??'#93c5fd'):'none'})];});
 for(const kind of ['heatmap','matrix'])r.register(kind,(p,t)=>{const data=p.data??[],cw=(p.width??500)/(data[0]?.length||1),ch=(p.height??400)/(data.length||1),max=p.max??Math.max(1,...data.flat().map(Math.abs));return data.flatMap((row:any[],y:number)=>row.flatMap((v:number,x:number)=>[n(`cell-${y}-${x}`,'Rect',{x:x*cw,y:y*ch,width:cw-2,height:ch-2,fill:p.selected?.[0]===y&&p.selected?.[1]===x?'#f97316':`rgb(${Math.round(240-Math.abs(v)/max*180)},${Math.round(246-Math.abs(v)/max*100)},250)`,ariaLabel:`row ${y}, column ${x}: ${v}`}),n(`value-${y}-${x}`,'Text',{x:x*cw,y:y*ch,width:cw,height:ch,text:String(v),fontSize:Math.min(28,ch*.4),textAlign:'center',fill:t.text??'#172033'})]));});
 r.register('table',(p,t)=>{const rows=[p.columns??[],...(p.data??[])],cw=(p.width??800)/Math.max(1,rows[0].length),ch=p.rowHeight??44;return rows.flatMap((row:any[],y:number)=>row.flatMap((v,x)=>[n(`bg-${y}-${x}`,'Rect',{x:x*cw,y:y*ch,width:cw,height:ch,fill:y===0?'#dbeafe':y%2?'#f8fafc':'white',stroke:'#e2e8f0'}),n(`text-${y}-${x}`,'Text',{x:x*cw+8,y:y*ch+4,width:cw-16,height:ch-8,text:String(v),fontSize:18,fill:t.text??'#172033'})]));});
 r.register('KPI',(p,t)=>[n('value','Text',{x:0,y:0,width:p.width??400,height:90,text:String(p.value),fontSize:64,fill:p.color??t.accent??palette[0]}),n('label','Text',{x:0,y:95,width:p.width??400,height:40,text:p.label??'',fontSize:24,fill:t.text??'#172033'})]);
 r.register('progress',(p,t)=>[n('track','RoundedRect',{width:p.width??400,height:p.height??24,radius:12,fill:'#e2e8f0'}),n('fill','RoundedRect',{width:(p.width??400)*Math.max(0,Math.min(1,p.value??0)),height:p.height??24,radius:12,fill:p.color??t.accent??palette[0]})]);
 r.register('network',(p,t)=>{const nodes=p.nodes??[],byId=Object.fromEntries(nodes.map((v:any)=>[v.id,v]));return [...(p.edges??[]).map((e:any,i:number)=>n('edge-'+i,'Arrow',{x:byId[e.from]?.x??0,y:byId[e.from]?.y??0,x2:byId[e.to]?.x??0,y2:byId[e.to]?.y??0,stroke:'#94a3b8',strokeWidth:2})),...nodes.flatMap((v:any)=>[n('node-'+v.id,'Circle',{x:v.x,y:v.y,radius:v.radius??24,fill:v.color??palette[0]}),n('label-'+v.id,'Text',{x:v.x-70,y:v.y+28,width:140,height:30,text:v.label??v.id,fontSize:18,textAlign:'center'})])];});
 r.register('timeline',(p,t)=>(p.data??[]).flatMap((v:any,i:number)=>[n('event-'+i,'Circle',{x:i*(p.width??800)/Math.max(1,p.data.length-1),y:40,radius:12,fill:i<=p.active?palette[0]:'#94a3b8'}),n('label-'+i,'Text',{x:i*(p.width??800)/Math.max(1,p.data.length-1)-50,y:65,width:140,height:80,text:v.label,fontSize:18})]));
 r.register('imageComparison',(p)=>[n('before','Image',{width:p.width,height:p.height,src:p.before}),n('after','Image',{width:p.width,height:p.height,src:p.after,clip:{x:0,y:0,width:p.width*(p.position??.5),height:p.height}}),n('divider','Line',{x:p.width*(p.position??.5),y:0,x2:p.width*(p.position??.5),y2:p.height,stroke:'#fff',strokeWidth:4})]);
 r.register('hotspotImage',(p)=>[n('image','Image',{width:p.width,height:p.height,src:p.src}),...(p.hotspots??[]).map((h:any,i:number)=>n('hotspot-'+i,'Button',{x:h.x,y:h.y,width:44,height:44,text:h.label??String(i+1),ariaLabel:h.description??h.label}))]);
 for(const kind of ['tabs','stepper'])r.register(kind,(p)=>{const items=p.items??[],w=(p.width??800)/Math.max(1,items.length);return items.map((v:any,i:number)=>n('item-'+i,'Button',{x:i*w,y:0,width:w-8,height:48,text:typeof v==='string'?v:v.label,fill:i===(p.active??0)?palette[0]:'#475569',value:i}));});
 r.register('carousel',(p)=>[n('slide','Image',{width:p.width,height:p.height,src:p.items?.[p.active??0]?.src??p.items?.[p.active??0]})]);
 for(const kind of ['tooltip','popover'])r.register(kind,(p)=>p.open?[n('background','RoundedRect',{width:p.width??300,height:p.height??100,fill:'#172033',radius:8}),n('content','Text',{x:12,y:12,width:(p.width??300)-24,height:(p.height??100)-24,text:p.text,fontSize:18,fill:'white'})]:[]);
 r.register('geoJSON',(p)=>geo(p));
}
export function geo(p:Dict):SceneNode[]{const width=p.width??800,height=p.height??500,scale=p.zoom??1,project=(v:number[])=>{let [lon,lat]=v;lat=Math.max(-85,Math.min(85,lat));return [(lon+180)/360*width*scale+(p.panX??0),(p.projection==='mercator'?(1-Math.log(Math.tan(Math.PI/4+lat*Math.PI/360))/Math.PI)/2:(90-lat)/180)*height*scale+(p.panY??0)];};const features=p.data?.features??[];return features.flatMap((f:any,i:number)=>{const g=f.geometry,props={fill:p.selected===i?'#f97316':f.properties?.fill??p.fill??'#93c5fd',stroke:'#334155',strokeWidth:1,ariaLabel:f.properties?.name??String(i)};if(g.type==='Point'){const [x,y]=project(g.coordinates);return[n('geo-'+i,'Circle',{...props,x,y,radius:6})];}if(g.type==='LineString')return[n('geo-'+i,'Polyline',{...props,fill:'none',points:g.coordinates.map(project)})];if(['Polygon','MultiPolygon'].includes(g.type)){const polygons=g.type==='Polygon'?[g.coordinates]:g.coordinates;return polygons.map((rings:any[],j:number)=>n(`geo-${i}-${j}`,'Path',{...props,fillRule:'evenodd',d:rings.map(ring=>'M'+ring.map(project).map(v=>v.join(',')).join('L')+'Z').join(' ')}));}throw new Error(`Unsupported GeoJSON ${g.type}`);});}
